### ISSUE TITLE
hello, I'm not receiving the data on arduino with LoRa with the same code,     i could see serial monitor for sender like:   Sending packet 0 Sending packet 1   but for reciever monitor output is like; Starting LoRa failed!

### ISSUE THREAD

**Issue by aniketmad** [sandeepmistry/arduino-LoRa#107]
hello, I'm not receiving the data on arduino with LoRa with the same code,     i could see serial monitor for sender like:   Sending packet 0 Sending packet 1   but for reciever monitor output is like; Starting LoRa failed!

**Comment by aniketmad** [comment]
![screenshot 16](https://user-images.githubusercontent.com/36538183/36462906-556f3186-16ec-11e8-89b7-05dd388b4a0a.png)
![screenshot 16](https://user-images.githubusercontent.com/36538183/36462930-71ef7334-16ec-11e8-8759-3caa6c121836.png)

**Comment by sandeepmistry** [comment]
@aniketmad please let us know what hardware you are using. As well as what you've done for far to debug the problem.

**Comment by aniketmad** [comment]
We are using Lora SX1276.We are getting garbage value while receiving data.

**Comment by aniketmad** [comment]
or maximum times we get:  "starting lora failed!" at receiver serial monitor

**Comment by morganrallen** [comment]
If you try LoraSender firmware on the receiver does it work?
Or do you get "starting lora failed"?

**Comment by aniketmad** [comment]
do you mean swiping sender and receiver??
yes it does work for this.

now i'm not starting lora failed.


NOW THE PROBLEM IS(OUTPUT):
LoRa Receiver
Received packet '' with RSSI -163    **# THIS COMES WHEN I remove NSS pin

**
Received packet '' with RSSI -159
Received packet 'Ia	⸮a	⸮Ia	⸮Ia	⸮Ia	⸮Ia	⸮Ia	⸮Ia	⸮Ia	⸮Ia	⸮Ia	⸮Ia	⸮Ia	⸮Ia	⸮Ia	⸮Ia	⸮Ia	⸮0Ia	⸮0⸮	Ia	⸮a	Ia	⸮Ia	⸮0⸮$⸮

**Comment by aniketmad** [comment]
i get either only **Lora Receiver** as heading and nothing below


or else when  i remove NSS pin i receive the abbove data with that garbage value.

please help me soon.

it's urgent

**Comment by conradholt** [comment]
I had the same problem, but I updated the standalone firmware for MKR WAN 1300, (that basically acts as a bootloader for the stm32) using the example MKRWANFWupdate_standalone inside the MKRWAN library and solved this issue.

**Comment by sandeepmistry** [comment]
Closing for now due to lack of activity.

**Comment by shivampandey3611** [comment]
sir I am sending values temprature and humidity but it is not able diffrentiate the values as well as not printing values on lcd print please suggest us some code.for devlopment purpose

**Comment by deanpretorius** [comment]
Hi. Was there any progress with this issue? I have the same issue and am not sure how to proceed with solving it.

**Comment by ClaytonMendes** [comment]
I'm sorry for my english, I'm having the same problem.
Any solutions to this problem?

**Comment by pkrishnavamsi0709** [comment]
i am having the same issue can anybody help me out

**Comment by pkrishnavamsi0709** [comment]
i am getting some unkown data

**Comment by pkrishnavamsi0709** [comment]
> We are using Lora SX1276.We are getting garbage value while receiving data.

did you get any solution this problem I am also getting the same issue

**Comment by Aishwaryakanna** [comment]
I am having same probelm with Lora-e220-900T22D

**Comment by morganrallen** [comment]
Lora-e220-900T22D is based on the LLCC68 chip, which is not supported by this driver.

**Comment by pkrishnavamsi0709** [comment]
> I am having same probelm with Lora-e220-900T22D

My problem is solved . In my condition firstly I am using esp for transmitting from lora and Arduino Uno for receiving later I changed both transmitter and receiver to Arduino Uno then it worked

**Comment by Srivardhan06** [comment]
same problem getting garbage values
