### ISSUE TITLE
transmitt over 1000 sensor, traffic may broke or how to collect message received?

### ISSUE THREAD

**Issue by halukmy** [sandeepmistry/arduino-LoRa#109]
i just make stress test and in loop stage , every milisecond send message

i just try to simulate 1000 sensor sends messages in 10 seconds,

so is it possible to collect all messages, and traffic may broke down?

because every sensor read every message with this library, except the lorawan

am i right or wrong?

and issuses? 

thanks

**Comment by sandeepmistry** [comment]
@halukmy I don't have any experience with this. You'll have to experiment yourself to answer.

If any boards send data at the same time with same or similar radio parameters, there will be collisions and data will be lost.
