### ISSUE TITLE
question : arduino-LoRa vs LoraWan

### ISSUE THREAD

**Issue by halukmy** [sandeepmistry/arduino-LoRa#110]
everybody please to add their thinks 

cons and pros this repo vs lorawan ?

first let me add

This Repo Pro : no need gateway
               cons : every node listen every other node

**Comment by BlackxRyan** [comment]
By the way can you use this library with LoRa Heltec and Seeeduino LoRaWAN ?

**Comment by wero1414** [comment]
With LoRAWAN you have Address of each device and the most important thing, SECURITY, cause when you transmit a packet with LoRA as any modulation else, any radio at the same frequency will receive the packet, so its important to encrypt in a safe way your data, another important thing in LoRaWAN is that you have a complete network where you can manage a lot of devices with different frequencies based on the sub-channel you select, with the frequencies multiplexed like that you'll have a more free spectrum to make communication more affordable.

LoRA by itself work as a M2M communication where you can send information with very low power by a great distance or as well in a noisy enviroment (speaking electromagnetically), it allows you that by the modulation nature

**Comment by sandeepmistry** [comment]
@wero1414 thanks for answering. Doesn't LoRaWAN encrypt data packets as back for the protocol stack?

Is this something to PR to the read me or a new FAQ document?
