### ISSUE TITLE
Accessing GPIO pins for LoRa Duplex

### ISSUE THREAD

**Issue by 3Dtj** [sandeepmistry/arduino-LoRa#116]
Sandeep and others,

I successfully used your LoRa Duplex code to pass a signal across two Arduino UNOs using an Adafruit RFM95 chip.  Now I want to use one of the RFM95's GPIO pins to illuminate a LED.   I've tried addressing the GPIO pin using pinMode (dio3, OUTPUT) and digitalWrite(dio3, HIGH) but that's not working.  

As always appreciate any suggestions.
3Dtj

**Comment by sandeepmistry** [comment]
Hi @3Dtj,

I suggest you look at the Semtech data sheet. Off the top of my head, I believe they are only used to output interrupt state and can't be controlled by the using - but I could be wrong.
