### ISSUE TITLE
Lara Ra-01 transmission of information to the maximum distance

### ISSUE THREAD

**Issue by SoliJohn** [sandeepmistry/arduino-LoRa#117]
Hello everybody.
I have two identical sensors Lara Ra-01 and two Arduino Nano. I assembled the schema and ran the sample programs "sender" and "reciver". Everything is working! But does not transfer to the long distance. Tell me how to manage with the range of information transmission? I need these modules to be transmitted as far as possible. The check is carried out in an open area, the receiving sensor will stand on the 8th floor and the transmitting sensor will be far from the house in the forest. Thank you in advance!

**Comment by sandeepmistry** [comment]
Hi @SoliJohn,

Please try the answer from https://github.com/sandeepmistry/arduino-LoRa/issues/125#issuecomment-379545493 - and let us know if it works.

We can re-open this ticket if the suggestion doesn't help.
