### ISSUE TITLE
Do not get data at receiver side ?

### ISSUE THREAD

**Issue by Joypacharya** [sandeepmistry/arduino-LoRa#120]
Hello !!!
I am using two Arduino UNO and two Lora Ra-01 module. 
As per your instruction, I connected all of the wire to my UNO, But it couldn't be worked. Then I put one another wire in between Dio1 and Uno pin 3 afterward it started sending the data. Another side I did the same thing and run receiver code but I did get any data. Tell me a solution to this problem. I tried with other libraries it works well but get some time wrong data. I hope you understand my problem.

**Comment by sandeepmistry** [comment]
Hi @Joypacharya,

Please see the answer in https://github.com/sandeepmistry/arduino-LoRa/issues/125#issuecomment-379545493

I think this is duplicate, so will close this for now and we can continue the discussion in #125.
