### ISSUE TITLE
LORA failed error

### ISSUE THREAD

**Issue by kayani009** [sandeepmistry/arduino-LoRa#123]
hi sandeep,
I am using two SX1276RF1IAS transceivers and using this code but every time it gives error Lora failed. i am using arduino uno board.
please help???

**Comment by aniketmad** [comment]
we are also facing same problem, "Starting LoRa Failed"

**Comment by morganrallen** [comment]
Duplicated of #115 and #122 (please don't open the same issue repeatedly)
