### ISSUE TITLE
how same interfacing Lora with Attiny85?

### ISSUE THREAD

**Issue by kadellabs** [sandeepmistry/arduino-LoRa#128]
hi I am using low power microcontroller i.e Attiny85, how can i use this library to achieve interfacing between lora and attiny85?

**Comment by sandeepmistry** [comment]
@kadellabs try the suggested pins outs from https://github.com/sandeepmistry/arduino-LoRa#semtech-sx1276777879-wiring.

Let us know if you have any issues.

**Comment by halukmy** [comment]
@kadellabs  did you make it?
