### ISSUE TITLE
problem compiling LoRaSender example :`SPISettings’ does not name a type`

### ISSUE THREAD

**Issue by yasharne** [sandeepmistry/arduino-LoRa#131]
Hi
When I want to compile LoRaSender example I get the following error:
```
In file included from LoRaSender.ino:2:0:
/home/yashar/sketchbook/libraries/LoRa/LoRa.h:84:3: error: ‘SPISettings’ does not name a type
   SPISettings _spiSettings;
```
How can I fix it?

**Comment by morganrallen** [comment]
What board are you targeting?

**Comment by yasharne** [comment]
arduino uno and nano

**Comment by sandeepmistry** [comment]
What about Arduino IDE and AVR core version?

My suggestion is to update to the latest Arduino IDE, very old versions did not support SPISettings in the SPI library.

**Comment by yasharne** [comment]
Thanks a lot for your help.
That solved my problem.
I was using arduino IDE downloaded via ubuntu package manager which is a very old version
