### ISSUE TITLE
Data not received in LoRa Ra-02 module

### ISSUE THREAD

**Issue by bharath-krishnaswamy** [sandeepmistry/arduino-LoRa#136]
I have LoRa Ra-02 modules connected to Arduino Uno. I think the Nicole is transmitting data from example "loratransmitter" , but the data isn't getting detected by the reciever . Please help.

**Comment by bharath-krishnaswamy** [comment]
Module*

**Comment by Garfius** [comment]
Remember the big(REALLY BIG) problem with this module about coupling and current consumption.

I has a similar problem to yours and solved it by using 1mm^2 secion cable for power, and power only from arduino circuit (remember 0.3v margin for interruption).

I was not receiving data, only the 1st packet, and remember this 100mw circuit is the hasdest to get working.
