### ISSUE TITLE
How to obtain the same data in another lora?

### ISSUE THREAD

**Issue by looi666** [sandeepmistry/arduino-LoRa#139]
I have built 20 lora network by using the duplex arduino coding by sending and receiving RSS...now I'm facing problem how to obtain all the data inside the 20 lora

**Comment by looi666** [comment]
The lora that I use is ra01 and the controller is Arduino nano

**Comment by sandeepmistry** [comment]
@looi666 please clarify what you are trying  to do + expand on what the issue is and re-open this issue.
