### ISSUE TITLE
assigning unique address to module

### ISSUE THREAD

**Issue by kadellabs** [sandeepmistry/arduino-LoRa#140]
1)hi i am working with 4 lora ra02 modules i need to assign address to each modules how to do it?
2)Also the coverage distance between tow lora is only 100mtrs 
     i)what is the maximum distance i can obtain?
     ii) What modifications i need to be done in order to get maximum range?

**Comment by sandeepmistry** [comment]
@kadellabs for 1) please see the FAQ section of the read me.

2) I suggest you do some search on the web about this.
