### ISSUE TITLE
LoRa receiver code not working

### ISSUE THREAD

**Issue by pritibakale** [sandeepmistry/arduino-LoRa#146]
Hello,

I am using examples from this LoRa library. When I used code LoRaSender then it is working fine and sends data. But to receive the message when I used LoRaReceiver code then,  it is not at all receiving anything.

Can anyone please suggest, what could be the issue?

**Comment by sandeepmistry** [comment]
@pritibakale are you passing the correct frequency into `begin` for the hardware you are using. Same applies to antenna setup

Depending on what h/w you are using, you might need to use the [setTxPower](https://github.com/sandeepmistry/arduino-LoRa/blob/master/API.md#tx-power) API to use PA BOOST for power.

**Comment by sandeepmistry** [comment]
Closing for now due to lack of feedback.
