### ISSUE TITLE
B-L072Z-LRWAN1 LoRa®/Sigfox™ Discovery kit 

### ISSUE THREAD

**Issue by bigboxthailand** [sandeepmistry/arduino-LoRa#149]
Does this library support this board ?

If yes , how do I set pin or use it .

I try to use the LoraSender and Lora Receiver in Example for transmit data between 2 boards but I got the message "Starting LoRa failed! "

Please Help !
 
https://community.st.com/community/stm32-community/blog/2017/04/05/lora-discovery-kit

**Comment by sandeepmistry** [comment]
@bigboxthailand have you looked at https://github.com/stm32duino/Arduino_Core_STM32/pull/221

**Comment by sandeepmistry** [comment]
Closing for now do to lack of feedback.
