### ISSUE TITLE
need urgent help

### ISSUE THREAD

**Issue by OMKAR29** [sandeepmistry/arduino-LoRa#15]
can this library work for sx1272 chip..if yes/no how can i make it work. the library and examples are very good and straightforward unlike other lora libraries. but i have sx1272 and and i want to use the this library and examples on my chip. please revert back as soon. thanks in advance.
[s1272.pdf](https://github.com/sandeepmistry/arduino-LoRa/files/948863/s1272.pdf)

**Comment by sandeepmistry** [comment]
Hi @OMKAR29,

As mentioned in the read me (https://github.com/sandeepmistry/arduino-LoRa#compatible-hardware) this library is only compatible with the SX1276/77/78/79.

You might be able to get it working with the SX1272 by comparing the datasheets and changing the library code in the appropriate areas. I have no plans to add SX1272 support, but would be open to merging a pull request if you or someone else provided one.
