### ISSUE TITLE
Dragino LoRa Shield + Ethernet Shield (W5100)

### ISSUE THREAD

**Issue by TupaNegreiros** [sandeepmistry/arduino-LoRa#156]
The documentation is not clear (even Dragino wiki).
In order to use "setPins", do I need to change jumpers SV2/SV3/SV4 positions?

I'm trying to use Dragino LoRa Shield together with Ethernet Shield (W5100), both shields use pin 10 as SS. Seems impossible to change SS on Ethernet Shield, and unclear how to change it on LoRa.

**Comment by sandeepmistry** [comment]
> In order to use "setPins", do I need to change jumpers SV2/SV3/SV4 positions?

Yes, then pass the pins to `LoRa.setPins(...)`.

**Comment by fer-g3** [comment]
I can´t make it work, I have an Arduino Uno + Shield Ethernet + Shield LoRa 915Mhz. I already change the pins with setPins function but it always return LoRa init failed. Check your connections.

**Comment by JuandreG** [comment]
Could you get this setup working? I'm having the same issue.
