### ISSUE TITLE
Implementing SX127x errata for 500KHz bandwidth

### ISSUE THREAD

**Issue by vasimv** [sandeepmistry/arduino-LoRa#157]
The Semtech did make an errata for the SX127x chips, stating it requres a bit manual tuning when bandwidth set to 500KHz. I've tried to implement it and it shows few db's increase on receiver.

Errata pdf: https://www.semtech.com/uploads/documents/sx1276_77_78-errata.pdf

[patch-errata.txt](https://github.com/sandeepmistry/arduino-LoRa/files/2090620/patch-errata.txt)

**Comment by torntrousers** [comment]
Thats interesting, a few db's is quite a significant change. I'll give it a try too. 
Doesn't your update need to take account of the frequency - the errata says use value 0x64 when  the frequency is above 862MHz?

**Comment by vasimv** [comment]
Oops, sorry, should say. I'm using 433MHz and you're right.

**Comment by sandeepmistry** [comment]
@vasimv please submit a pull request for this.

**Comment by IoTThinks** [comment]
Already fixed.
https://github.com/sandeepmistry/arduino-LoRa/blob/master/API.md#signal-bandwidth
