### ISSUE TITLE
How to set AppsKey and NwsKey?

### ISSUE THREAD

**Issue by TomHyhlik** [sandeepmistry/arduino-LoRa#158]
This library does not provide AES encryption? Do I have to program it by myself to be able to use the arduino node or I can leave the message unencrypted?

**Comment by TomHyhlik** [comment]
Thank you very much 👍

**Comment by halukmy** [comment]
@wero1414  can you share aes eencryypted message sample

**Comment by wero1414** [comment]
@halukmy this library explains how to encrypt your message you need a key in the tx and the rx https://github.com/DavyLandman/AESLib .

This example is in the readme

 `Serial.begin(57600);
uint8_t key[] = {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15};
char data[] = "0123456789012345"; //16 chars == 16 bytes
aes128_enc_single(key, data);
Serial.print("encrypted:");
Serial.println(data);
aes128_dec_single(key, data);
Serial.print("decrypted:");
Serial.println(data);`

**Comment by wero1414** [comment]
Closing cause doubt solved, and provide an aes example

**Comment by halukmy** [comment]
@wero1414  i got 2 question for you
t
hanks for share first..

can we secure our message from sniffers?

and second is, do you have got Class-C for LoRaWAN in Lmic code?

thanks bro
