### ISSUE TITLE
can we secure communication with xxtea algorythim?

### ISSUE THREAD

**Issue by halukmy** [sandeepmistry/arduino-LoRa#161]
https://github.com/boseji/xxtea-iot-crypt

i just find this crypt algorythim

so can we secure our lora message from sniffers with that algorythim?

thanks

**Comment by Yury-MonZon** [comment]
Of course. You can use any encryption that you like, just mind the extra bytes added.

**Comment by sandeepmistry** [comment]
Duplicate of https://github.com/sandeepmistry/arduino-LoRa/issues/155.
