### ISSUE TITLE
Sync Word defaults to 0x12

### ISSUE THREAD

**Issue by giampiero7** [sandeepmistry/arduino-LoRa#163]
Hi,
I was trying this library on an Arduino MKR WAN 1300 to communicate with a Pycom board.
It wouldn't work until I explicitly called `LoRa.setSyncWord(0x34);`
The default sync word seems to be 0x12, as opposed to what is stated in the documentation (0x34).
Cheers

**Comment by morganrallen** [comment]
Unless I'm reading the datasheet wrong, `0x34` is the `LoRaWAN` sync word.

From page 115
**Reg:*** `RegSyncWord (0x39)`
**Bits:** `0-7`
**Name:** `SyncWord`
**Mode:** `rw`
**Reset:** `0x12`
**Description:** `LoRa Sync. Word Value 0x34 is reserved for LoRaWAN networks`

**Comment by giampiero7** [comment]
Yes, but the documentation of this library (https://github.com/sandeepmistry/arduino-LoRa/blob/master/API.md#sync-word) says the default sync word is 0x34

**Comment by morganrallen** [comment]
PR #175

**Comment by sandeepmistry** [comment]
Closed via #175.
