### ISSUE TITLE
LoRa Sender Starting LoRa failed!

### ISSUE THREAD

**Issue by mavericks123** [sandeepmistry/arduino-LoRa#164]
Hello,

I have a problem with sending and receiving data. 

I followed steps like on your post, but serial monitor says:

LoRa Sender
Starting LoRa failed!

A code:

```
#include <SPI.h>
#include <LoRa.h>

int counter = 0;

void setup() {
  Serial.begin(9600);
  while (!Serial);
  LoRa.begin(433E6);

  Serial.println("LoRa Sender");

  if (!LoRa.begin(433E6)) {
    Serial.println("Starting LoRa failed!");
    while (1);
  }
}

void loop() {
  Serial.print("Sending packet: ");
  Serial.println(counter);

  // send packet
  LoRa.beginPacket();
  LoRa.print("hello ");
  LoRa.print(counter);
  LoRa.endPacket();

  counter++;

  delay(5000);
}
```

![img_5122](https://user-images.githubusercontent.com/16475634/41844320-24b5cefc-7870-11e8-8ac9-c661c2849c5d.JPG)
![img_5123](https://user-images.githubusercontent.com/16475634/41844330-2c6e9a98-7870-11e8-8fa3-19f7179785b0.JPG)
![img_5124](https://user-images.githubusercontent.com/16475634/41844331-2c966852-7870-11e8-870d-389fdaf70f47.JPG)

**Comment by Yury-MonZon** [comment]
Looks like LoRa is not responding. Check the cabling, power etc.

**Comment by morganrallen** [comment]
@mavericks123 You need to ensure the pins are all mapped correctly.

SPI pins `MISO`, `MOSI`, `SCK`, `SS` need to be connected to the Uno's SPI pins
```
10 (SS),
11 (MOSI),
12 (MISO),
13 (SCK)
```

Then you need to ensure your `RESET` and `DIO0` pins match *or* call [setPins](https://github.com/sandeepmistry/arduino-LoRa/blob/master/API.md#set-pins)

It's hard to tell from the pictures but it does seem you're setup fairly close but it's worth looking over everything closely.

**Comment by sandeepmistry** [comment]
Closing this for now due to lack of activity.
