### ISSUE TITLE
LoRa.begin() works. But LoRa.beginPacket,LoRa.endPacket() and LoRa.print() not working

### ISSUE THREAD

**Issue by pritirathi14** [sandeepmistry/arduino-LoRa#166]
Hi Sandeep,

I am interfacing LoRa sx1276 with Arduino MEGA. The connections are all good. The setup code of Arduino is working fine.
```
void setup() {
  // put your setup code here, to run once:
  Serial.begin(9600);
  delay(500);
  while (!Serial);

  Serial.println("LoRa Sender");

  if (!LoRa.begin(868E6)) {
    Serial.println("Starting LoRa failed!");
    while (1);
  }
}
```
=======================

But below lines are not working
```
  LoRa.beginPacket();
  LoRa.print(ktc.readCelsius());
  LoRa.endPacket();
```
execution seems to be halted at the LoRa.beginPacket() line.

**Comment by Yury-MonZon** [comment]
Try 
```
      LoRa.beginPacket();
      LoRa.print("Test");
      LoRa.endPacket();
```

**Comment by pritirathi14** [comment]
Its not working.
Even if I try 

LoRa.beginPacket();
      LoRa.print("Test");
      LoRa.endPacket();
Serial.println("Hello");

the serial print is also not working. Seems control is stuck at the LoRa.beginPacket() line.

**Comment by Yury-MonZon** [comment]
I'm afraid that I have to see the whole code in order to crack it. Drop it to pastebin and link here.

**Comment by sandeepmistry** [comment]
@pritirathi14 please see 
https://github.com/sandeepmistry/arduino-LoRa/issues/166#issuecomment-401247819, also you might want to try with an external 3.3V power supply.

**Comment by sandeepmistry** [comment]
Closing this for now due to lack of activity.

**Comment by taherrera** [comment]
I am using the MKRWAN1300. For me it hanged when the buffer was "big" (8 bytes or more). I noticed the SPI frequency was 250kHz, kinda low.. anyway when I increased the frequency it never worked, so further decreasing the SPI frequency to 200kHz made it work for me..

An other problem I had, and I hope it helps somebody else: it does not work without the external antenna !! 

ps: MKRWAN1300 sucks, what a waste of money..

**Comment by bcaceres96** [comment]
Has anyone managed to solve the error?
