### ISSUE TITLE
Lora Duplex Problem

### ISSUE THREAD

**Issue by WillingLearner** [sandeepmistry/arduino-LoRa#167]
Hello. I have two Lora Ra-02 module and arduino uno. I tried to perform duplex example (that is I tried to communicate these two modules with each other ) but I failed. The modifications I made on that sketch :

- I set frequency to 433 mhz
- I used defult pinout (ss = 10 , reset = 9, irq = 2 )

I upload the same sketch into arduino and lora pairs. And then What I saw in the serial monitor is :+1: 
 
LoRa Duplex
LoRa init succeeded
Sending HeLoRa World! (Data is sent for once not continuously)

Afterwards nothing happens, neither sending nor receiving.

What can my problem be ?

Thanks in advance!

**Edit: Problem was solved !**

**Comment by cpsinghopl** [comment]
Dear WIllingLearner, how was it solved?
