### ISSUE TITLE
Esp32 SX1278 compability

### ISSUE THREAD

**Issue by craxen** [sandeepmistry/arduino-LoRa#168]
Hello, im trying to use your magnificient library with my ESP32 \SX1278 module, this does not work, could you perhaps fix it ?

Im trying the nolora sketches, and i get complaints about avr\progmem missing.
I would love to be able to control all my rc-switches.

Other library functions seem to work with my ttgo lora besides the remotec.

Marten

**Comment by morganrallen** [comment]
This sounds like you're not setting your board correctly in the Arduino interface but need more info to be sure.

**Comment by craxen** [comment]
Hello, ok, but all your other examples compile and work on the same board,
hmm, im going to try it again and give you some debug info.
Thanks

Den tors 26 juli 2018 17:50morganrallen <notifications@github.com> skrev:

**Comment by morganrallen** [comment]
> Im trying the nolora sketches, and i get complaints about avr\progmem missing.
I would love to be able to control all my rc-switches.

What are the "nolora sketches" ?

**Comment by craxen** [comment]
Hello, i refer to the examples for remote control named noloraxxxx in your
examples folder

Den sön 29 juli 2018 20:09morganrallen <notifications@github.com> skrev:

**Comment by sandeepmistry** [comment]
There is no `noloraxxxx` example in this repo: https://github.com/sandeepmistry/arduino-LoRa/tree/master/examples
