### ISSUE TITLE
Compatibility with Semtech SX1272 board

### ISSUE THREAD

**Issue by bibaswan** [sandeepmistry/arduino-LoRa#171]
Hi, this is less of a issue more of a question does this library support the Semtech SX1272 Chip, I am just getting started with LoRa and i got my boards of RS

here is the link: https://uk.rs-online.com/web/p/lower-power-rf-modules/9033059/

i just want to know if this library will support it out of the box or if there is something extra I need to do, I been trying to get it to work for the past hour checked all the wiring but nothing seems to happen. thanks for the help in advance.

**Comment by sandeepmistry** [comment]
This library is not compatible with the SX1272, please see the supported hardware list in the read me.
