### ISSUE TITLE
TxDone callback is not working

### ISSUE THREAD

**Issue by rustam-iskenderov** [sandeepmistry/arduino-LoRa#173]
Hi,
I've been recently playing with SX1278 and found that onReceive callback is called only for RxDone
While according to datasheet it should be called for any interrupt, including TxDone.

It's mapped to DIO0 and should handle both callback for receive and callback for send.
Though when I'm sending data, callback is not called at all.

**Comment by morganrallen** [comment]
You are correct this isn't implemented. Issue #63 is the previous discussion on the issue and #62 is a work in progress PR that needs some attention. I will look into that as soon as I can.
