### ISSUE TITLE
Can this code be used with a e44-ttl-100 LoRa radio?

### ISSUE THREAD

**Issue by jeprince** [sandeepmistry/arduino-LoRa#182]
I have two 915mhz E44-TTL-100. It has the pins GND,VCC,AUX,Txd,Rxd,M1, and M0. can i use this code to set up a Reciever and A transmitter?

**Comment by morganrallen** [comment]
At a guess I would say no. It appears that device has it's own on board controller talking to the SX127x radio. This driver is meant to talk directly to the SX127x.
