### ISSUE TITLE
CRC - How to check it on the Receiver?

### ISSUE THREAD

**Issue by saramonteiro** [sandeepmistry/arduino-LoRa#196]
Hi, 
I am starting to use LoRa.h right now, and I enabling CRC in the transmitter in the setup function. But how should I check it on the Receiver?
thanks in advance!

**Comment by morganrallen** [comment]
Closing this as it's known there is no way to be notified when a CRC error occurs. A feature request has been outlined in #326

**Comment by mcgurk** [comment]
> The library doesn't currently do a lot with CRC check aside checking if the radio set the CRC Error flag. So, if you've called `enableCrc` on **both** the transmitter and the receiver, you should either receive the packet if there is no error, else `parsePacket` will return 0.

`enableCrc` does nothing when used with receiver. Datasheet page 30: "On the receiver side, the bit RxPayloadCrcOn in the register RegModemConfig1 is not used"

**Comment by morganrallen** [comment]
This was a great catch @mcgurk, I will be pulling in your PR next week.
