### ISSUE TITLE
How to remap SCK, MISO and MOSI to other GPIO in ESP32?

### ISSUE THREAD

**Issue by oblansundar** [sandeepmistry/arduino-LoRa#197]
Hi,
I am using ESP8266 with Nodemcu lolin v3. I wanted to use this library since it uses the same ESP. But how to remap the pins as i dont have GPIO 19,23 and 18 in Nodemcu and Wemos boards?

**Comment by ddrmax** [comment]
you can do this before calling LoRa.begin(freq);
`
//example for Heltec Wifi 32 LoRa
SPI.begin(5, 19, 27, 18);
LoRa.setPins(18, 14, 26);
`
here is the SPI. begin function in SPI.h in the Arduino ESP32 package:
` void begin(int8_t sck=-1, int8_t miso=-1, int8_t mosi=-1, int8_t ss=-1);`
