### ISSUE TITLE
LoRa Addressing with Raspberrypi 

### ISSUE THREAD

**Issue by anggelliafisca** [sandeepmistry/arduino-LoRa#209]
I have 3 LoRa sender connect to esp 32 and 4 LoRa receiver connect raspberry pi
How can I addressing the LoRa in raspberrypi?
I have already can addressing LoRa sender using library LoRa duplex
Can you help me?
thanks

**Comment by morganrallen** [comment]
Addressing is not something that is provided by this library, it's up to you to provide addressing structure on top of the plain LoRa data packet. We do though provide an example of some very basic addressing concepts here https://github.com/sandeepmistry/arduino-LoRa/blob/master/examples/LoRaDuplex/LoRaDuplex.ino
