### ISSUE TITLE
Compiling for IOT2020

### ISSUE THREAD

**Issue by Causticpain** [sandeepmistry/arduino-LoRa#21]
Hello,

I'm trying to compile the LoRa Receiver example on a Simatic IOT2020 (which is basically a intel Galileo Gen2), but during the compiling I get these issuses:

C:\Users\hladik\Documents\Arduino\libraries\SPI.h/SPI.h:1843:8: error: 'SPIClass' does not name a type

C:\Users\hladik\Documents\Arduino\libraries\LoRa.h/LoRa.h:74:3: error: 'SPISettings' does not name a type

Could somebody help me with this?

By the way: when I compile it for a Arduino Mega 2560 everything runs propertly.

**Comment by sandeepmistry** [comment]
This is an issue with the SPI library you manually installed in `C:\Users\hladik\Documents\Arduino\libraries\SPI.h/SPI.h`.

Also, this library requires an SPI library that supports the SPI transactions.
