### ISSUE TITLE
parsePacket() returning zero

### ISSUE THREAD

**Issue by durraniii** [sandeepmistry/arduino-LoRa#220]
#include <EEPROM.h>
#include <LoRa.h>

uint8_t nodeId,destination;

void setup()
{
  Serial.begin(9600);
  while(!Serial);

  
   if (!LoRa.begin(433E6))
    Serial.println("failed");
 
  nodeId = 1; //every node will have its own id
  EEPROM.write(0, nodeId);
  uint8_t readVal = EEPROM.read(0);
  Serial.print(F("NodeId: "));
  Serial.println(readVal);
   
  
}

void forward(uint8_t target)
{

  LoRa.beginPacket();
  LoRa.print("hello");
  LoRa.print("from");
  LoRa.print(target);
  LoRa.endPacket();
  
}

void loop()
{
  
  destination=2;
    
 int packetSize = LoRa.parsePacket();
 Serial.print(packetSize);
    
  if (packetSize) {
    
    // received a packet
    Serial.print("Received packet,now checking destination ");
if(destination==nodeId)
{
    // read packet
    while (LoRa.available()) {
      Serial.print((char)LoRa.read()); 
    }

    // print RSSI of packet
    Serial.print("' with RSSI ");
    Serial.println(LoRa.packetRssi());
  
  }
else
{
  Serial.println("target was not me, packet forwarded !");
  
}

}
  
  
  
}

the parse packet function is returning zero. where is the problem? kindly help

**Comment by IoTThinks** [comment]
It is normal for LoRa.parsePacket() to return 0.
There is no LoRa packet during LoRa.parsePacket().

So you either use receiveCallback or just skip LoRa.parsePacket() with 0.
