### ISSUE TITLE
2-Way communication

### ISSUE THREAD

**Issue by braedynscode** [sandeepmistry/arduino-LoRa#226]
<h1>LoRa 2-Way Communication</h1>
Hi, My IT Class is working with <b>ESP32 T-Beam boards</b> with LoRa built in,
and I was wondering if there is a way to send <b>AND</b> receive at the same time on the same board.
there is only one Rx/Tx Antenna per board if that means any difference.

**Comment by morganrallen** [comment]
Have a look at the duplex examples. https://github.com/sandeepmistry/arduino-LoRa/blob/master/examples/LoRaDuplexCallback/LoRaDuplexCallback.ino
