### ISSUE TITLE
Error when receiving data corrupted

### ISSUE THREAD

**Issue by sabas1080** [sandeepmistry/arduino-LoRa#227]
Hi

I am testing with two arduino MKR1300 one as master sends another as slave receiving, when I start receiving data I have corrupt data, example

```
Sat3,3649,494,-46.39,34235.34,8269.14,10.61,87.00,41685,-1.486573,-121
Sat3,4045,555,-46.14,34675.73,8181.34,10.40,87.00,41.654308,-1.485965,-121
Sat3,4945,692,-45.61,35579.51,8003.88|1.Q7,87.00,R1.65399.1-484798,-121
Sat3,6027,857,-44.85,36535.32,7820.19,11.65,87.00,41.653900,-1NwU�^,-121
Satx`pq.651833,-1.<01�15,9061.9�0391,32.298>84,-121 <--- here init data corrupted
Sat3,7992,11ub�6	+:Ay�%�6&��5ԇ��`	�k����O�A�8���l[�U��q3��`�n>�,-121
Sat�!0�.651546,-1^.n=0,826���^0U p39.16�x<�,-122
```

It seems that you are reading garbage. Any possible reason?

Thanks!

**Comment by morganrallen** [comment]
This is not an uncommon occurrence.
Many factors can cause this to happen but most frequently it is some combination of..

* distance too great
* Coding Rate and/or Spread Factor are too low for given distance.
* Low quality antenna
* Bad frequency matching between sender/receiver (can be checked with `LoRa.packetFrequencyError()`)

This can also be prevented by enabling CRC on both the sender and receiver using `LoRa.enableCrc()` though it should be noted, while this can improve reception, if a packet it too badly garbled it will be dropped.
