### ISSUE TITLE
Led pin 13 overridden on Nano board?

### ISSUE THREAD

**Issue by cb88** [sandeepmistry/arduino-LoRa#23]
So, As soon as I use LoRa.begin()

I Lose control of pin 13 on my Clone Nano... I checked and the blink sketch works just fine. Is there a reason for this I didn't see any off hand looking at the code but I may have missed something?

**Comment by sandeepmistry** [comment]
This library uses SPI: https://github.com/sandeepmistry/arduino-LoRa#semtech-sx1276777879-wiring

On the Nano and Uno, the SPI SCK pin is connected to pin 13, so the LED cannot be used.

**Comment by cb88** [comment]
Ah I hadn't realized that... thanks.
