### ISSUE TITLE
Numbers don't show correctly

### ISSUE THREAD

**Issue by panosss** [sandeepmistry/arduino-LoRa#232]
My Sender sends a message with this code:

> void loop() {
  Serial.print("Sending packet: ");
  Serial.println(counter);
  // send packet
  LoRa.beginPacket();
  LoRa.print("hello ");
  LoRa.print(counter);
  LoRa.endPacket();
  counter++;
  delay(5000);
}

My Receiver receives with this code:
> void loop() {
  display.clearDisplay();
  // try to parse packet
  int packetSize = LoRa.parsePacket();
  if (packetSize) {
    // received a packet
    display.setTextSize(1);
    display.setTextColor(BLACK);
    display.setCursor(0,0);
    display.println("Received packet '");
    display.display();
    // read packet
    while (LoRa.available()) {
      display.print((char)LoRa.read());      
      display.display();
    }
    // print RSSI of packet
    display.print("' with RSSI ");    
    display.println(LoRa.packetRssi());
    display.display();
  }
}

The result on the receiver 's screen (5110 with the library Adafruit_PCD8544):
Received packet 'el 1 ' with RSSI  -24   (instead of 10, or 11 or 12 etc it displays 'el 1 ')
or: Received packet 'el 2 ' with RSSI  -24 (instead of 20, or 21 or 22 etc it displays 'el 2 ')

Maybe somebody knows how to fix this?

(I 've used as a reciever an Arduino and now an ESP8266. This happens to both)

**Comment by YogoGit** [comment]
```
// read packet
while (LoRa.available()) {
display.print((char)LoRa.read());
display.display();
}
```
Try:
```
// read packet
while (LoRa.available()) {
  display.print((char)LoRa.read());
}
display.display();
```

**Comment by panosss** [comment]
I tried it, no change.

**Comment by panosss** [comment]
Solution: in the tsansmitter I had to convert the int counter to String:
`// send packet
  LoRa.beginPacket();    
  LoRa.print(String(counter));
  LoRa.endPacket();  `
