### ISSUE TITLE
calling any function in the callback method

### ISSUE THREAD

**Issue by squeakus** [sandeepmistry/arduino-LoRa#234]
Hi, 
I have adapted your excellent example [to test the battery during deep sleep](https://github.com/squeakus/bitsandbytes/tree/master/LoRa/batteryClient). One problem I noticed is it hangs if I put any function call in the receive function, even if that function only contains methods that are also used in the callback function. Does the receive callback also block function calls as well streaming functions.

My apologies for flagging this as an issue as it is more to do with the Lora library than your code but I have been googling for an hour and cannot find any similar mention of this problem.

**Comment by IoTThinks** [comment]
You should not call any function in a callback method.
If the function has any delay(), it may not be executed as you expect.

You can set a flag in the callback method. Then check the flag and execute it in the loop.
