### ISSUE TITLE
Pairing of LoRa Sx1278

### ISSUE THREAD

**Issue by MaazSk** [sandeepmistry/arduino-LoRa#245]
Hi, 
I am having 3 pairs of LoRa SX1278 I want to make pair such that one transmitter will transmit to only one receiver like we have pipe in Nrf 24l01+ do we have some provision for pairing the SX1278 LoRa?
Thanks and Regards.

**Comment by wero1414** [comment]
Hi, no theres no pairing here, you just set a frequency and the talk over that frequency if anyone is on Rx mode with the same frequency, spreadFactor and bandwidth will receieve that information.

You can define channels to communicate between each nodes (Each node a frequency to transmit and another to receive)
