### ISSUE TITLE
setSyncWord

### ISSUE THREAD

**Issue by gioreva** [sandeepmistry/arduino-LoRa#246]
When i Set setSyncWord i receive only receive one in 10 sent.
What can it be ?

Arduino uno, Ra-07 Ai-Thinker
LoRaDuplexCallback

**Comment by wero1414** [comment]
Did you change the syncWord in each device?

**Comment by gioreva** [comment]
Some number work, other number not work.
Smal number not work, 0, 1, 2
Need higher number
