### ISSUE TITLE
LORA Buffer Range issue

### ISSUE THREAD

**Issue by ankur209** [sandeepmistry/arduino-LoRa#265]
I want to transmit more than 400 characters but i cant able to do that because max_packet_length is only 255. I increased that length but it seems not working. Kindly help me to resolve the issue please.

**Comment by morganrallen** [comment]
The internal TX FIFO memory is only 255 bytes so this is the physical maximum amount of memory available. You should figure out a way to split your message.

This can be accomplished pretty easily, I can think of 3 methods worth exploring.

**Split Packet by Type**
If you're sending different types of data in one large packet, try splitting them into smaller, related data types. You may need a small header to indicate what the data type it contains is.

**Packet Header**
Include a packet header indicating how much data is being sent and how much more data is left.
In your example of 400 bytes a header could look something like this

```
struct Packet {
  uint8_t len;
  uint8_t packets_left;
  char *data;
} Packet_t;

Packet_t packet;
packet.len = 250; // send first 250 bytes
packet.packets_left = 1; // there is still more data
memcpy(&packet.data, &buf, 250);

send(&packet);

packet.len = 150; // send last 150 bytes
packet.packets_left = 0; // this is the last packet in this message
memcpy(&packet.data, &buf[250], 250);

send(&packet);
```

This is very much pseudo-code but should give you an idea of what a packet might look like. `packets_left` could also be bytes left.

**Packet Encoding**
There are ways you can encode a packet so the receiving end will know when the end of the packet has been reached. One I particularly like for LoRa is [COBS](https://en.wikipedia.org/wiki/Consistent_Overhead_Byte_Stuffing). It only add 1 bytes for every 255 bytes in the message making it very light weight and there are plenty of examples to choose from (even that link has a basic implementation).

Hope this gives you some info to go on.
