### ISSUE TITLE
LoRa.begin() fails when using SD.

### ISSUE THREAD

**Issue by horellana** [sandeepmistry/arduino-LoRa#266]
I have an arduino nano with a lora antenna connected with a SD module. The following code fails when the SD Module is connected to the arduino:

```
void setup() {
 
  Serial.begin(9600);
  while (!Serial);
 
  Serial.println("Lora Receiver");
  LoRa.setSPIFrequency(8E6);
  if (!LoRa.begin(433E6)) {
    Serial.println("Starting LoRa failed ");
    while (1);
  }

   Serial.begin(9600);
   if (!SD.begin(4)) {
     Serial.println("SD Init failed");
  }
 
  LoRa.setSpreadingFactor(10);
  LoRa.setSignalBandwidth(255E3);
 LoRa.crc();
}
```

With the message: ```Starting LoRa failed ```.

Lora is using SS 10, SD is using SS 4.

**Comment by morganrallen** [comment]
You probably need to call [setPins](https://github.com/sandeepmistry/arduino-LoRa/blob/master/API.md#set-pins), reopen if this doesn't fix your issue.
