### ISSUE TITLE
the main issue in this library, we have no API for clear received data or initiallize the receiving data pointer. if any time two Lora are unsync give unwanted error     

### ISSUE THREAD

**Issue by sahilsoni1** [sandeepmistry/arduino-LoRa#286]
Are you receiving `Starting LoRa failed` while using the demo code?

PLEASE see the [FAQ #1](https://github.com/sandeepmistry/arduino-LoRa#faq) about using [setPins](https://github.com/sandeepmistry/arduino-LoRa/blob/master/API.md#set-pins) **BEFORE** submitting an issue.

**Comment by morganrallen** [comment]
Please submit new issue with a detailed explanation of the issue you're having, include a minimal test case that will help resolve your issue.
