### ISSUE TITLE
Problem to initialize LoRa with nodemcu.

### ISSUE THREAD

**Issue by Alexfante** [sandeepmistry/arduino-LoRa#29]
Hi!

When I start LoRa, (! LoRa.begin (868E6)) my nodemcu does not start, I press the reset and it restarts itself. If I remove the LoRa boot from the program, it stops reinitializing. What could it be?

I tested it with 2 arduinos and it works. I used the example scketchs from the LoRa library.
![lora_esp](https://user-images.githubusercontent.com/29732663/27750557-b2923da6-5dae-11e7-967c-bfea837ee17a.png)
![erro esp2](https://user-images.githubusercontent.com/29732663/27750605-e5db585a-5dae-11e7-82b8-bf5f24960321.png)

**Comment by Alexfante** [comment]
I've updated the links.
![lora_esp](https://user-images.githubusercontent.com/29732663/27842635-0a109042-60e2-11e7-9aab-35dbcdb6afd7.png)

I may even be being naive, but I think it should work.

#include <SPI.h>
#include <LoRa.h>

void setup() {
  Serial.begin(9600);
  while (!Serial);
  Serial.println("LoRa Receiver");
  LoRa.setPins(8, 2, 1);
  if (!LoRa.begin(868E6)) {
    Serial.println("Starting LoRa failed!");
    while (1);
  }
}

void loop() {
  // try to parse packet
  int packetSize = LoRa.parsePacket();
  if (packetSize) {
    // received a packet
    Serial.print("Received packet '");

    // read packet
    while (LoRa.available()) {
      Serial.print((char)LoRa.read());
    }

    // print RSSI of packet
    Serial.print("' with RSSI ");
    Serial.println(LoRa.packetRssi());
  }
}

**Comment by Alexfante** [comment]
It's working, apparently my arduino installation on windows 10 is in trouble. I made the same build in Fedora and it's working.

**Comment by fxsh1301** [comment]
@Alexfante 
Hi sir!
Do you have any project that using LoRa with Raspberry Pi ?
