### ISSUE TITLE
MKR WAN 1310 not working when using Library Manager

### ISSUE THREAD

**Issue by thomasguenzel** [sandeepmistry/arduino-LoRa#303]
I've installed the 0.6.1 version using the Arduino Library Manager. Unfortunately, this version doesn't include the updated `#if defined(...1300) || defined(...1310)` precompiler directive.

The examples just end up printing `Starting LoRa failed!`. However, when using the master version, everything works just fine.

It would be great if you could bump the version :)

**Comment by sandeepmistry** [comment]
Hi @thomasguenzel,

I've just pushed a `0.7.0` tag that includes @facchinm's changes from pull request #297.

It should be available in the library manager in the next hour or so.
