### ISSUE TITLE
Recieved data if there is a person in between 2 lora sx1278 transceiver modules ( receive and transmit)

### ISSUE THREAD

**Issue by paulcastor30** [sandeepmistry/arduino-LoRa#305]
hello i am having problem with my lora sx1278 module. if there is no person standing between 2 lora sx1278 the data recieved looks like the data below, which is the data i want to transmit:		
----> 11/10/2019||8:17:43;Water Level;29;Soil Moisture;652;Raining;0;Count;8830;Water Pump;0;
but if there is a person / people standing in between the 2 lora sx1278 modules the data recieved looks like this:
---->?!!>00/2019||1:a:S6[1bteqdLevmd[@ZSmI!LkistureCountCountWater Pup
can you help me? do i need  a level shifter for this kind of problem? connections are good since i make it work.

**Comment by IoTThinks** [comment]
You can try to enableCRC on each node to drop corrupted packets.
And try to make your message...shorter to reduce packet corruption.
https://github.com/sandeepmistry/arduino-LoRa/blob/master/API.md#crc
