### ISSUE TITLE
MKRWAN 1310 using SPI flash.

### ISSUE THREAD

**Issue by 03sarath** [sandeepmistry/arduino-LoRa#308]
Hey sandeepmistry,

 Just now I got my new **MKR WAN 1310** boards from Arduino Store. I'm stuck in using an external  **SPI FLASH 2MB**.I'm using [Marzogh](https://github.com/Marzogh/SPIMemory) library for accessing SPI FLASH chip, I'm a bit confused in searching for **Slave Select pin**, I don't know which pin I have to use as Slave Select for accessing SPI flash.

According to schematic FLASH, chip has been connected to PIN `PB08` on SAMD21

**Comment by facchinm** [comment]
Hi @03sarath ,
you can access the external flash using pin 32 as CS https://github.com/arduino/ArduinoCore-samd/blob/master/variants/mkrwan1300/variant.h#L220  and `SPI1` as bus

**Comment by disk91** [comment]
You basically need more than this. I've made a custom firmware to be able to deactivate the UART on lorawan modem without having to reset it.
https://github.com/disk91/mkr1310_openLoRaModem_fw_update
