### ISSUE TITLE
How to using the mode fsk for module RA-02.

### ISSUE THREAD

**Issue by ohpattaya** [sandeepmistry/arduino-LoRa#31]
I want to test some things, a performance comparison between fsk mode with lora mode. But the problem exactly define REGISTER for fsk mode, so I asked for advice, or write liberry fsk mode for me, please respond. THANK YOU.

**Comment by sandeepmistry** [comment]
@ohpattaya FSK mode is not supported, this library is LoRa mode only.

**Comment by Youunesse** [comment]
You can download new library for SX1278 , it's supported FSK and LORA mode
the register for lora are different with fsk , it isn't the same
