### ISSUE TITLE
MKRWAN 1310 Battery charging mode is not working.

### ISSUE THREAD

**Issue by 03sarath** [sandeepmistry/arduino-LoRa#312]
Hey Guys,

Thanks in advance.

**My Li-ion battery is not getting Recharged**

1. I'm testing the recharging capacity of MKR WAN 1310
2. Trying to read battery status

**1.I'm testing the recharging capacity of MKR WAN 1310**

My MKRWAN 1310 is connected with Li-Ion battery(For JST connector) and used USB for external power supply. But my battery is not getting recharged. There is no output voltage at JST connector. Just wondering what is my mistake.

**2. Trying to read battery status**

I can see in `variant.cpp` of [MKRWIFI 1010](https://github.com/arduino/ArduinoCore-samd/blob/5dced38e81e6001a4b6e237e3462bc8db962127a/variants/mkrwifi1010/variant.cpp#L228), We have support for reading Battery Status by using `ADC_BATTERY`.

```
void initVariant() {
#if defined(USE_BQ24195L_PMIC)
  pinMode(ADC_BATTERY, OUTPUT);
  digitalWrite(ADC_BATTERY, LOW);
  delay(10);
  pinMode(ADC_BATTERY, INPUT);
  delay(100);

  bool batteryPresent = analogRead(ADC_BATTERY) > 600;
  if (batteryPresent) {
    enable_battery_charging();
  }
  disable_battery_fet(!batteryPresent);
#endif

  // NINA - SPI boot
  pinMode(NINA_GPIO0, OUTPUT);
  digitalWrite(NINA_GPIO0, HIGH);

  // disable NINA
  pinMode(NINA_RESETN, OUTPUT);
  digitalWrite(NINA_RESETN, HIGH);
}
```

But in **MKRWAN 1310** [ADC_BATTERY ](https://github.com/arduino/ArduinoCore-samd/blob/5dced38e81e6001a4b6e237e3462bc8db962127a/variants/mkrwan1300/variant.h#L67)is connected as [FLASH_CS](https://github.com/arduino/ArduinoCore-samd/blob/5dced38e81e6001a4b6e237e3462bc8db962127a/variants/mkrwan1300/variant.h#L220), Still is that possible to read battery status.

**Comment by morganrallen** [comment]
This issue is unrelated to LoRa, try asking in either the Arduino forums or the MKRWAN repo.

https://www.arduino.cc/en/Reference/MKRWAN
https://www.arduino.cc/en/Guide/MKRWAN1300
https://github.com/arduino-libraries/MKRWAN
