### ISSUE TITLE
SX1272 supported?

### ISSUE THREAD

**Issue by Btje1977** [sandeepmistry/arduino-LoRa#313]
Not really an issue but would the library work with the SX1272?

**Comment by IoTThinks** [comment]
May be you can try your own first.
In the docs, they seems not supporting sx1272.
However, they look similar. Don't know if the registers are the same.

https://github.com/sandeepmistry/arduino-LoRa#compatible-hardware

**Comment by ricaun** [comment]
The SX1272 uses different register e some work totally different, It's not possible without change each register and checks each function.
I goona try! 😃
