### ISSUE TITLE
Not an Issue - LoRa Shield Update

### ISSUE THREAD

**Issue by kd8bxp** [sandeepmistry/arduino-LoRa#32]
Thank you for the library, and work you have done on this.
I am currently doing some tests and getting some pretty amazing results.
So this is just for your information - Linksprite's LoRa Shield also works with the library 
(it does appear to use PIN 2 for interrupt) 
It is using the RF96 chip.
It appears to be very similar to the Dragino LoRa Shield.
Your library is the only one that I got to work with my boards BTW - the sketch that Linksprite provides doesn't compile.  Beyond what you need to know: (I suspect it has something to do with the IDE they used, but even using the one they have pictured, I got weird errors) 
Here is a link to some information that is helpful for the Linksprites shield
http://linksprite.com/wiki/index.php5?title=DIY_low-cost_LoRa_gateway_based_on_pcDuino#2._Program_Arduino_Uno

Thanks again.

**Comment by sandeepmistry** [comment]
@kd8bxp nice!

If you thinks it's worth adding a link to the read me, please open a pull request :)

Closing for now, but feel free to continue the discussion.
