### ISSUE TITLE
failed CRC packet info

### ISSUE THREAD

**Issue by artemen** [sandeepmistry/arduino-LoRa#325]
Hi, is there a way to receive information that a packet was received, but failed checksum? for example if hopping this would still indicate proper sync between sender/receiver, though indicate that there was interference on the channel.
thanks!

**Comment by morganrallen** [comment]
Sadly no, there is no mechanism for report a CRC error has occurred. This functionality should be added, as the data is still contained in the FIFO buffer and there are some use cases (user readable text) were that data is still useful. As always, PRs welcome.
