### ISSUE TITLE
how to get data from child lora devices to parent lora 

### ISSUE THREAD

**Issue by tvjmohan** [sandeepmistry/arduino-LoRa#33]
I have tried the simple sender and receiver. its working fine. thank you for the detailed explanation.

i wold like to know how this communication is working with out mentioning any address to these devices. ?

and i wanted to know how the communication can be done from single to multiple lora devices ?

**Comment by sandeepmistry** [comment]
> i wold like to know how this communication is working with out mentioning any address to these devices. ?
> and i wanted to know how the communication can be done from single to multiple lora devices ?

LoRa at the radio level is all broadcast, no addressing. You'll have to build you're own addressing scheme into the data payload.

**Comment by tvjmohan** [comment]
ok thank you. sandeep.
