### ISSUE TITLE
ttgo lora esp32 has so bad rssi values when they are so close why?

### ISSUE THREAD

**Issue by halukmy** [sandeepmistry/arduino-LoRa#336]
i have sx1276 ttgo lora, when they close it should be like - 8 or even -15 rssi right?

when i get close  i got like rssi -40 or -50 rssi value, is that normal?

i use everything for make it boost like 

 LoRa.setTxPower(20, PA_OUTPUT_PA_BOOST_PIN );
  LoRa.setSpreadingFactor(10);

anybody can handle it?

i got stock antenna and device working at around 840- 868 mhz

**Comment by mcgurk** [comment]
I would first check antennas. Stock antennas can be for totally wrong frequencies and other uses than LoRa. Good antenna can be made from 86mm long single wire (for 868MHz). I get -25 rssi with 14dBm power (14dBm/25mW is maximum in my country).
![lora_antenna](https://user-images.githubusercontent.com/22012544/74194564-2d601900-4c62-11ea-9273-3d8c427f27c5.jpg)

**Comment by IoTThinks** [comment]
With short and Chinese antenna, normally I only get around -50 to -40 RSSI within 20cm.

So it is normal in my viewpoint.
You can change to a better antenna but I heard the RSSI may not be so accurate within too-short distance.

**Comment by beowulff** [comment]
I’ve never seen better than -50 or so at 2-3 feet distance, even with hand-tuned antennas that will transmit over 2 miles at ground level. So, I wouldn’t worry about trying to get much better than you currently have.
(I realize that this is an old topic, but other people might be interested.)

**Comment by IoTThinks** [comment]
Really?
I intend to make my own antenna like @mcgurk to see if I can do better than -40 dBm RSSI.

**Comment by beowulff** [comment]
Can you post a link to that Antenna?
I have a nice Anritsu spectrum analyzer, and I made a hand-tuned dipole connected to an SMA connector, and got excellent range, but still not better than around -48 at close range. The RF section on most of these LoRa modules is questionable - it’s hard to match an antenna, since there is no access to the antenna feed point before the matching network. 

Also, at close distances, you are within the Fresnel Zone, and tiny movements will have a big affect on performance, as will any object nearby.

IMHO, the best way to determine antenna performance is in the field - no obstructions and at least 100m of distance between transmitter and receiver.

**Comment by IoTThinks** [comment]
You check the second post in this topic for the handmade antenna.

People said need to measure in at least several meters away.

Im just not happy enough for not reaching something better than -40 dBm RSSI.

May be the dipole or tripole antenna may help?

Your antenna is single wire antenna, right?

**Comment by beowulff** [comment]
I made a  1/4 wave dipole antenna - two wires at 180° from each other.
I also have made a 1/4 wave monopole antenna, but that requires a large ground plane.

The antenna in post #2, is not optimal. It is a monopole, but has little to no ground plane. You can increase its efficiency greatly by adding an equal-length wire to the ground connection on the LoRa module, at 180° to the antenna wire.

**Comment by IoTThinks** [comment]
Then I believe your test result is reliable.
Dipole antenna is often very good.

Just wonder how others get under -40dBm RSSI.

May be due to PA or RFO? Or other aspects?

**Comment by beowulff** [comment]
Here is my Dipole antenna:
![IMG_7575](https://user-images.githubusercontent.com/5475119/83472515-4886ac80-a43c-11ea-9ba3-e52ac85295bd.jpg)

Note that Monopole antenna are slightly more efficient, but require a large (infinite is best) ground plane.

**Comment by IoTThinks** [comment]
I use a 17+cm bronze wire as single wire antenna. 
Also get around 40+ dbm only.

One of my friends use the below antenna .
Simply soldered to Ai-Thinker ra01.
Can reach -24 or -15 RSSI within a few meters.

![image](https://user-images.githubusercontent.com/29994971/83935841-a70aac80-a7e7-11ea-8eed-c900d8e95bce.png)

May be in short range, a good antenna can not give better RSSI number below -40dbm.
May be in long range, there will be different?

From RSSI and SNR, how to reliable test the quality of the signal?
