### ISSUE TITLE
Semtech  datasheet 404

### ISSUE THREAD

**Issue by Basilisvirus** [sandeepmistry/arduino-LoRa#339]
You mention Semtech datasheet, http://www.semtech.com/images/datasheet/sx1276.pdf in LoRaSimpleNode in examples, gut the link does not work.

**Comment by IoTThinks** [comment]
Just only need to Google for new Semtech specs.

**Comment by morganrallen** [comment]
Oh yeah, they switched to saleforce or some other nonsense and now it's super hard to find. 

https://www.mouser.com/datasheet/2/761/sx1276-1278113.pdf
