### ISSUE TITLE
nrf52-lora(RA-02 module)

### ISSUE THREAD

**Issue by safwan9633** [sandeepmistry/arduino-LoRa#342]
hi 

i am using LoRa module RA-02 in  nrf52832  try to send 400bytes per sec but i can only send 256bytes per sec .how can i send 2 packet per sec(512bytes per sec)?

how can i increase datarates in lora without missing packets and bytes?

**Comment by IoTThinks** [comment]
What are your current SF and BW (Hz) setting?

**Comment by safwan9633** [comment]
hi
@IoTThinks  SF= 8,BW=125KHZ

**Comment by IoTThinks** [comment]
SF6, BW500 is the fastest at 37kbps.
The faster the data rate, the shorter the distance.

**Comment by safwan9633** [comment]
hi
@IoTThinks  i need 3kbps  with getting long distance
is it possible to send 2 packet(256bytes) per sec with sf 8 and bw 125khz?

**Comment by IoTThinks** [comment]
Hi,
You can help yourself here
https://www.rfwireless-world.com/calculators/LoRa-Data-Rate-Calculator.html
