### ISSUE TITLE
LoRa E32 TTL support?

### ISSUE THREAD

**Issue by halukmy** [sandeepmistry/arduino-LoRa#344]
is there any LoRa E32 TTL support?

**Comment by IoTThinks** [comment]
Nope. No support.
Inside LoRa E32 is STM8+SPI LoRa sx1278. It has its own firmware in stm8.

Unless you want to hack the module.

**Comment by halukmy** [comment]
can you share how to hack?

**Comment by IoTThinks** [comment]
You can Google around.
Inside have uart pin.
Btw, the module may stop working if you remove the metal cover.

I see it is not worth the effort.
Just use it as it is or use a raw SPI sx1278 chip.
