### ISSUE TITLE
Lora sx 1278 initialization of the lora sx1278 failed

### ISSUE THREAD

**Issue by feras33** [sandeepmistry/arduino-LoRa#349]
Hello 
Dear all, 
I have been trying to connect lora sx1278 on the arduino mega 2560. I followed all the steps on github but still failing in transmitting.Can any one review the steps with me?

**Comment by IoTThinks** [comment]
Show the photos of your hardware setup, codes and pin connection.

Noone would be able to do a blind guess.

**Comment by feras33** [comment]
Thanks for your assistance. I have too many wiring conections in my project but i will explain what i have connected for the lora.
 LORA------------MEGA

MOSI------------51
SCK-------------52
MISO-----------50
NSS-------------10
RESET-----------9
DIO0-------------2
3.3 V from the arduino to the lora sx1278 
And the ground connection to the ground 

I am using SPI.h and LoRa.h Library. I have used the code from the library just to  make sure that it is operating well. The one that sends hellow word and increment the number of counts each it transmits this sentence. But it keep telling me to lora failed.

**Comment by Karanc141** [comment]
if you add a Serial.println(version) here: https://github.com/sandeepmistry/arduino-LoRa/blob/master/src/LoRa.cpp#L87 - what is the value?

**Comment by Karanc141** [comment]
if you add a return Serial.println(version) here: https://github.com/sandeepmistry/arduino-LoRa/blob/master/src/LoRa.cpp#L120 - what is the value?

**Comment by feras33** [comment]
there is an error
class 'LoRaClass' does not have any field named '_onTxDone'

**Comment by IoTThinks** [comment]
@feras33 TxDone is only available in latest zip clone of this lib.

If you use the lib via Arduino IDE, then it is old version 0.7.0. There is no txDone.

**Comment by IoTThinks** [comment]
@morganrallen Please help to push Release v0.7.1 to Arduino Library.
Otherwise, the examples will not match with the v0.7.0 in Arduino library.

**Comment by IoTThinks** [comment]
![d7da5887c8c1fe662f4e42413696df69](https://user-images.githubusercontent.com/29994971/77241990-6e1d5b80-6c2c-11ea-8677-4f5269c955d4.png)

SS shoud be pin 53 instead.
If LoRa can not set SS low then init LoRa failed.

I believe in Arduino, you need to follow the default pinout.

In esp32, can change the SS pin to any pin.

**Comment by morganrallen** [comment]
> @morganrallen Please help to push Release v0.7.1 to Arduino Library.
> Otherwise, the examples will not match with the v0.7.0 in Arduino library.

Doh! I pushed the commit but forgot to tag the release. I've done and pushed that now, it can take some time to show up in the Library Manager but is on it's way. Good catch @IoTThinks , thanks!

**Comment by morganrallen** [comment]
Well, it might have already been published? Everyone sure it's up to date? Were the examples pull directly from this repo?

**Comment by IoTThinks** [comment]
@morganrallen Awesome. I will check the Arduino IDE on Monday for new release.

Normally, I copy the examples from github but install the library from Arduino IDE.

Thanks for your effort.

**Comment by feras33** [comment]
i have updated the latest version 0.7.1 .I am getting a new error.
Error compiling for board Arduino Mega or Mega 2560.

**Comment by morganrallen** [comment]
Two points here
First, this error is incomplete and doesn't help us debug this issue.
Second, we run build tests against this device and they are passing, so this is likely something in your code.

**Comment by feras33** [comment]
I have been trying to do all what is mention on github. The lora chip still not working can you provide a picture of setup or coding to check on my arduino, Because the library code it is compiled but still not working.

**Comment by feras33** [comment]
By the way nss pin is the same as ss pin? Because there is no nss pin on arduino mega.

**Comment by Karanc141** [comment]
Yes, it is same. SS is Slave Select and NSS is new Slave Select.

**Comment by Karanc141** [comment]
https://github.com/sandeepmistry/arduino-LoRa/issues/349#issuecomment-602058094

**Comment by IoTThinks** [comment]
Try to change to SS to pin 53.

**Comment by IoTThinks** [comment]
Try to change to SS to pin 53. 
I believe the pins for SPI in Arduino may be fixed.

**Comment by feras33** [comment]
I tried it, but still no use.

**Comment by IoTThinks** [comment]
You can learn from this friend. https://github.com/sandeepmistry/arduino-LoRa/issues/351
At least he can send something with Mega 2650. :D

**Comment by IoTThinks** [comment]
I made Mega + sx1278 works at https://github.com/sandeepmistry/arduino-LoRa/issues/205#issuecomment-613848638
