### ISSUE TITLE
Starting LoRa failed

### ISSUE THREAD

**Issue by Karanc141** [sandeepmistry/arduino-LoRa#350]
I have tried everything from changing spi pins, spi frequency.
Even tried almost all releases of this library.
I have the exact same connection as shown in library.
I tried with both Nano  (with external 3.3V power supply) and Uno(with logic level convertor) boards.
I have 3 LoRa SX1278 boards and tried using all of them.
I am struggling for past 3 weeks.
I even tried to reinstall Arduino IDE.
None of this works.
What should I do next ?

**Comment by IoTThinks** [comment]
Show the photos of your hardware setup, codes and pin connection.

Noone would be able to do a blind guess.
