### ISSUE TITLE
lora sx 1278 ra-02  433MHz connections 

### ISSUE THREAD

**Issue by feras33** [sandeepmistry/arduino-LoRa#354]
hello 
i have been trying to connect my lora sx1278 on my arduino mega 433Mhz , but i keep getting intializing lora failed. Can you give me some detailed help about the default connection between arduino mega 2560 ,and lora sx1278 ra-02.

Thanks.

**Comment by IoTThinks** [comment]
Check this and update the library to v0.7.2
https://github.com/sandeepmistry/arduino-LoRa/issues/351

**Comment by feras33** [comment]
Still not working probably the chip is damage. Thank you

**Comment by IoTThinks** [comment]
I made Mega + sx1278 works at https://github.com/sandeepmistry/arduino-LoRa/issues/205#issuecomment-613848638
