### ISSUE TITLE
Arduino Nano 33 IoT

### ISSUE THREAD

**Issue by skuppens** [sandeepmistry/arduino-LoRa#355]
Hi,

I was wondering if your code also works with the Arduino Nano 33 IoT.
It doesn't give any errors when compiling. Output seems OK 
`11:07:12.328 -> LoRa init succeeded.
11:07:12.328 -> 
11:07:12.328 -> LoRa Simple Node
11:07:12.328 -> Only receive messages from gateways
11:07:12.328 -> Tx: invertIQ disable
11:07:12.328 -> Rx: invertIQ enable
11:07:12.328 -> 
11:07:12.328 -> Send Message!
11:07:12.396 -> TxDone
11:07:13.324 -> Send Message!
11:07:13.392 -> TxDone
11:07:14.349 -> Send Message!
`
But when I check the Gateway I have (One from TTN, indoor model) I don't see any message arriving). Also not sure If I should see them, but I would like them to be visible somewhere.
Trying to get this to work with TTN. 
The LIMC libraries give errors on the IRQ pins or something.

Using the Nano 33 IoT board with a LoRA RFM95C module/breakout from Adafruit
Any thoughts on how to tackle this one?
Kindest regards,

**Comment by IoTThinks** [comment]
Your gateway may be a LoRaWAN gateway.
This library is LoRa.

They are not compatible.

**Comment by skuppens** [comment]
That’s true…
My mistake, looked over that.

Thank you

Stijn

Van: IoTThinks.com <notifications@github.com>
Verzonden: donderdag 2 april 2020 14:42
Aan: sandeepmistry/arduino-LoRa <arduino-LoRa@noreply.github.com>
CC: Kuppens Stijn <stijn.kuppens@kdg.be>; Author <author@noreply.github.com>
Onderwerp: Re: [sandeepmistry/arduino-LoRa] Arduino Nano 33 IoT (#355)


Your gateway may be a LoRaWAN gateway.
This library is LoRa.

They are not compatible.
