### ISSUE TITLE
question how do I make 2 modules transmit in full duplex using 2 arduino to send data via serial to the pc?

### ISSUE THREAD

**Issue by manotroll** [sandeepmistry/arduino-LoRa#357]
I don't understand much about programming on Arduino and I couldn't find a code that way

in the case and the sx1278 and I saw that it allows change of protocol and bandwidth in his technical file
is there any code example like that?

**Comment by IoTThinks** [comment]
You have to do your own.
[Arduino 1 => LoRa] <=>[LoRa => Arduino 2 => UART] <=> PC
