### ISSUE TITLE
how we can set address to lora module.

### ISSUE THREAD

**Issue by tvjmohan** [sandeepmistry/arduino-LoRa#36]
i want to work with 3 lora modules.  all 3 should have address. so that i can send the data from 3 lora modules to another lora module is 4 rth one.   so how i can give address to particular lora module.

**Comment by tvjmohan** [comment]
issue is addressed in another question. thank you.

**Comment by 3Dtj** [comment]
What was the answer to the question?  How do you assign the local address?  Completely new to this and first attempt at using LoRa.

Thanks,
Travis
