### ISSUE TITLE
LoRa.parsePacket stop receiving packet

### ISSUE THREAD

**Issue by Frederic-R** [sandeepmistry/arduino-LoRa#372]
I'm using this LoRa libary on a T-Beam board and after a while, it does not receive packet.

It does not happen when a I the onReceive listener and the device is in continuous receive mode. It then works flawlessly.

Is there any limitation on using the parsePacket method and calling it repeatedly ?

**Comment by IoTThinks** [comment]
If there is some more code running in main loop and parsePacket has little time left to run (and receive a packet if any)
onReceive is faster as it uses interrupt.
