### ISSUE TITLE
What is the length of thepreamble?

### ISSUE THREAD

**Issue by Portia-Lin** [sandeepmistry/arduino-LoRa#373]
Hello. I want to calculate data rate in bps.

I used the following lora settings
Spread Factor: 12
Bandwidth: 62.5
The table shows that the data rate will be 146 bits per seconds.

![Table 10](https://i.piccy.info/i9/154e0a16918e6f3c315d141c92b71db4/1591558389/19660/1382453/table15.png)

The structure of the package is shown in the figure:

![Packet Structure](https://i.piccy.info/i9/eb6428ed79ebedafc3a8b65d5fdbb8b0/1591558823/54494/1382453/packet_structure.png)

Now i want to calculate how many seconds my message will be transmitted. I need to know the programmed length of the preamble. What is it for your library? And maybe you can tell me how to calculate the length of the header.
Then I will be able to know the length of the whole packet and calculate the transmission time

**Comment by Portia-Lin** [comment]
In the library, I found tapes that are responsible for the length of the preamble:
#define REG_PREAMBLE_MSB         0x20
#define REG_PREAMBLE_LSB         0x21
But I still don't understand the length ...

**Comment by IoTThinks** [comment]
Check here https://www.loratools.nl/#/airtime

**Comment by Portia-Lin** [comment]
Thank you, there is a standard length 8 symbols. 0x20 and 0x21 are listed in the library. What is the length of 0x20? I don`t understand this

**Comment by morganrallen** [comment]
Those are the address location for the preamble length setting. Unfortunately we do not provide a way to read that back yet, but if you have not changed it, it will stay at the default of 0.

Section 4.1.1.7 explains how to calculate airtime.

**Comment by Portia-Lin** [comment]
Therefore, the length of the preamble is 0?

**Comment by Portia-Lin** [comment]
I tried to calculate it and I don't understand what max(numeric, 0) means. And I don't know if I'm doing it right.

![Image](https://i.piccy.info/i9/1168a3713c1092040d644c304f778378/1591659483/19174/1382453/datar.png)

**Comment by IoTThinks** [comment]
The preamble should be > 0 as it is used to detect if a packet is a LoRa packet.
You can set it here: https://github.com/sandeepmistry/arduino-LoRa/blob/master/API.md#preamble-length.

The wording says: Supported values are between 6 and 65535.

I believe transferring a preamble bit or a normal data bit take the same period of time.

**Comment by Portia-Lin** [comment]
But how to calculate the function max ()

**Comment by Portia-Lin** [comment]
Now i want to use the center frequency of channel 4 of LPD433 - 433.150. I inserted the following code:
```
LoRa.begin(433.150E6)
```
Everything works, but does it really work at this frequency?

**Comment by IoTThinks** [comment]
I checked with my SDR.
This library really set the frequency right with LoRa AI-Thinker.

**Comment by Portia-Lin** [comment]
> I checked with my SDR.

Thank you very much!
