### ISSUE TITLE
Confirmation of data transfer from transmitter to receiver?

### ISSUE THREAD

**Issue by Portia-Lin** [sandeepmistry/arduino-LoRa#375]
I am developing a system with many sensors (10 pieces). After sending a signal to the sensors, they must transmit information to the receiver. The signal is sent to all sensors at the same time, so immediately after that they will start sending data. But because they send a signal at the same time, the receiver will not receive all the signals. How to get out of this situation? Or in the absence of confirmation, the sensors send the signal again, how to do it?

**Comment by Arismane** [comment]
Why not programming each sensor to have a different small delay before starting to send the data from the time it received the signal so the receiver doesn't have a problem with the reception?

**Comment by brainelectronics** [comment]
@Portia-Lin you could request an ACK from each sensor. This ACK could be sent by each sensor after recieving the signal from the master, and the master could send an ACK to the sensor after receiving their sensor value.
This works of course only if you do not send a broadcast message.
Check my PR #406
