### ISSUE TITLE
Lora sx 1276 Dragino shield initialization of the lora sx1276 failed on arduino uno

### ISSUE THREAD

**Issue by kengbalap25** [sandeepmistry/arduino-LoRa#380]
Hello
Dear all,
I have been trying to connect lora dragino shield on the arduino uno. I followed all the steps on github but still failing in transmitting.Can any one review the steps with me on set pin?

**Comment by IoTThinks** [comment]
Your photo of the hardware wiring and your code?

And be sure of the pin mapping.

**Comment by IoTThinks** [comment]
What did you do the resolve the issue?
