### ISSUE TITLE
433Mhz Poweroutlets with LoRa ?

### ISSUE THREAD

**Issue by mega-hz** [sandeepmistry/arduino-LoRa#386]
Hi,

i am trying to send a code to switch a 433Mhz Poweroutlet, but they dont react.

Is it possible to switch those outlets with a LoRa RA-01 at all?

With those cheap Tx / Rx Modules on ebay it works, but too less distance.

Can you help?

Wolfram. (arduino-at-mega-hz.de)

**Comment by IoTThinks** [comment]
Last time, we even have LoRa power plug (ESP32+ RA01/Ra02 + Relay)
Quite easy.

Then the rest is up to your coding skill. Should be trivial, too.

https://github.com/IoTThinks/EasyLoraPlug
