### ISSUE TITLE
Changing modulation?

### ISSUE THREAD

**Issue by stl1988** [sandeepmistry/arduino-LoRa#387]
I have a M5Stack and a LoRa 433 module  which uses this library. The description of the module says it supports multiple modulation modes like FSK, GFSK etc. How can I change the modulation inside my code?

**Comment by IoTThinks** [comment]
This library is for LoRa only.

For FSK, can try RadioLib.
https://github.com/jgromes/RadioLib/blob/master/examples/SX127x/SX127x_FSK_Modem/SX127x_FSK_Modem.ino
