### ISSUE TITLE
Can it run FHSS?

### ISSUE THREAD

**Issue by Rita-GE** [sandeepmistry/arduino-LoRa#391]
Dear author,
I wonder can SX1278 achieve FHSS function through this lib?
I have seen this in another issue:
![image](https://user-images.githubusercontent.com/53596746/90365046-d10a0600-e097-11ea-9761-a5255496d0d7.png)
But to increase the success rate of data reception, this function plays a key role.

**Comment by IoTThinks** [comment]
Newer Chinese LoRa modules have DIO2.
https://resource.heltec.cn/download/Wireless_Stick_Lite/Wireless_Stick_Lite.pdf

But what is FHSS used for?

**Comment by Rita-GE** [comment]
FHSS (frequency hopping spread spectrum) is a method of transmitting radio signals by shifting carriers across numerous channels with a pseudorandom sequence which is already known to the sender and receiver.
For more detail, please see [here](https://www.techopedia.com/definition/25709/frequency-hopping-spread-spectrum-fhss).
The module I used is [Ra-02 AI-thinker](http://wiki.ai-thinker.com/_media/lora/docs/c048ps01a1_ra-02_product_specification_v1.1.pdf).
As SX1278's [datasheet](https://cdn-shop.adafruit.com/product-files/3179/sx1276_77_78_79.pdf) shows, it has that function on page 32.
![image](https://user-images.githubusercontent.com/53596746/90462703-d0c34680-e13b-11ea-9314-969d6e683a53.png)
I'm so curious why don't you know that.

**Comment by wero1414** [comment]
This library does not support FHSS now we're open to pull requests to be implemented, thanks!
