### ISSUE TITLE
Sending while in receive callback

### ISSUE THREAD

**Issue by markusschweitzer** [sandeepmistry/arduino-LoRa#393]
Hi,
Im using the latest version from git and this example: https://github.com/sandeepmistry/arduino-LoRa/blob/master/examples/LoRaReceiverCallback/LoRaReceiverCallback.ino

When I try to send a packet in the receive callback, (beginPacket, write, endPacket) the receiver sends the packet, but doesnt receive anymore.

Calling Lora.idle() and LoRa.receive() after the sending helps for a few packets, but eventually it stops receiving.

Any idea how I can make this work?

best regards,
markus

**Comment by IoTThinks** [comment]
Did you connect MCU to LoRa DIO0?
By right, in the library, the sending will be skipped if a packet is receiving.

**Comment by markusschweitzer** [comment]
Yes, the ISR gets called correctly (DIO0 is connected), I read all the data and send a response packet :/

**Comment by IoTThinks** [comment]
By right, you can not send a message during a receive.
This is chip limitation.

Send after the receiving is complete.
And sending outside the ISR callback.

**Comment by markusschweitzer** [comment]
Ok, I wasnt aware of that. Is there any way to do this without a periodic call in the loop() function?

**Comment by IoTThinks** [comment]
By right, you should not do any processing inside the ISR also.
ISR should set a flag only.
Then you can process sending or receiving in the main loop or in a FreeRTOS task.

```
void onReceive(int packetSize) {
  // received a packet
  Serial.print("Received packet '");

  // read packet
  for (int i = 0; i < packetSize; i++) {
    Serial.print((char)LoRa.read());
  }

  // print RSSI of packet
  Serial.print("' with RSSI ");
  Serial.println(LoRa.packetRssi());
}
```

**Comment by IoTThinks** [comment]
100ms is more than enough.

**Comment by IoTThinks** [comment]
Seems solved.
