### ISSUE TITLE
Adding LNA Support for sx1278?

### ISSUE THREAD

**Issue by IoTThinks** [sandeepmistry/arduino-LoRa#399]
Hi guys,
It seems that this library does not support LNA gain yet?

![image](https://user-images.githubusercontent.com/29994971/93665292-82d59180-fa9f-11ea-9cb2-683d70430319.png)

I believe LNA gain can help sx1278 to receive packet near -140dBm RSSI and below -21 SNR.
Therefore, it could help to receive packets farther.

This library has hasGain function for this purpose: https://github.com/jgromes/RadioLib/blob/master/src/modules/SX127x/SX1278.cpp#L316

Any supporting idea?

**Comment by IoTThinks** [comment]
@morganrallen @sandeepmistry Do you have any idea on this?
Thanks a lot. :D

**Comment by sandeepmistry** [comment]
@IoTThinks do you have a proposed API(s) in mind? Would you be able to pull request for this?

NOTE: `LnaBoostHf` is currently set to 0x03 in [begin(...)](https://github.com/sandeepmistry/arduino-LoRa/blob/master/src/LoRa.cpp#L134).

**Comment by IoTThinks** [comment]
@sandeepmistry May be, I will create my very first Pull request :D 
So by default, the LnaBoostHf is set to enable LNA for high frequency 868-923Mhz?

![image](https://user-images.githubusercontent.com/29994971/94516198-7a274d00-024f-11eb-8aea-a5493a6778b7.png)

Do you think we need to set LnaBoostLf for low frequency like 433Mhz?
![image](https://user-images.githubusercontent.com/29994971/94516307-bc508e80-024f-11eb-8a69-ef79642c814f.png)

**Comment by IoTThinks** [comment]
I'm able to make it works.
I will make a function setGain(byte gain).
Gain is from 0 to 6.

If the gain is 0, then AGC will be on.

![image](https://user-images.githubusercontent.com/29994971/94994846-7f282b80-05c4-11eb-8f60-74052e7dd2bf.jpeg)

I realize that LNA in HF 868/915/923 is better than LF 433 Mhz in default gain 0.
Therefore, RSSI for HF is better than for LF 433Mhz.

With AGC off and gain 6, I can now have RSSI -20 with two 433Mhz nodes in 20cm.

Will try to make it works and create a pull request.

**Comment by IoTThinks** [comment]
Added pull request at https://github.com/sandeepmistry/arduino-LoRa/pull/408
