### ISSUE TITLE
Reading temperature register

### ISSUE THREAD

**Issue by goran-mahovlic** [sandeepmistry/arduino-LoRa#4]
Is it possible to get temperature reading from REG_TEMP register?
I have tried but it always returns 0 :(
currently Im using your library in one GPS node that I have plan to put in car, and on one node that is connected to wifi router.
https://yadi.sk/d/1L3khXql37NVZA

**Comment by sandeepmistry** [comment]
@goran-mahovlic from page 92 in the data sheet it is only supported in FSK mode.

![screen shot 2017-01-15 at 8 10 09 pm](https://cloud.githubusercontent.com/assets/1163840/21968081/b8cf63ba-db5e-11e6-8e4f-d78d193c2fa7.png)

**Comment by XenonofArcticus** [comment]
Would an option be to briefly configure the chipset for FSK mode, sample the temperature, then switch back?

Obviously the chipset mode COULD affect the temperature, but especially when operating in a cold outdoor situation, I think the environmental impact on the temperature is much larger than the chipset functionality influence.
