### ISSUE TITLE
Point to MultiPoint

### ISSUE THREAD

**Issue by darshit115** [sandeepmistry/arduino-LoRa#40]
Dear Sandeep mistry,

can i make point to multi point communication using this library? if yes than how i can?  
i am making student project using LoRa in which i have to send data from one master unit to multiple slave units.
So, Please Help me.

Thanks and Regards,
Darshit

**Comment by sandeepmistry** [comment]
Please see the duplex example (https://github.com/sandeepmistry/arduino-LoRa/blob/master/examples/LoRaDuplex/LoRaDuplex.ino) for an example of how to add your own addressing scheme to LoRa packets which are broadcasted.
