### ISSUE TITLE
parsePacket() returns zero in duplex mode and from both ends its only transmitting the data not receiving in any side.

### ISSUE THREAD

**Issue by AjayJassal55** [sandeepmistry/arduino-LoRa#405]
I'm not getting any sensor data at receiving end of both node and gateway side. Please help me to out from it

**Comment by IoTThinks** [comment]
Option 1: If parsePacket() ==0, skip it. There is not always a LoRa packet coming when you use this command.
Option 2: Use callbackReceiver instead for continuous receiving.

**Comment by AjayJassal55** [comment]
> Option 1: If parsePacket() ==0, skip it. There is not always a LoRa packet coming when you use this command.
> Option 2: Use callbackReceiver instead for continuous receiving.

Is callbackreceiver is suitable for duplex mode when i also send the data from reciever. the int data.

**Comment by IoTThinks** [comment]
https://github.com/sandeepmistry/arduino-LoRa/blob/master/examples/LoRaDuplexCallback/LoRaDuplexCallback.ino
