### ISSUE TITLE
Card possibilities 

### ISSUE THREAD

**Issue by KRolander** [sandeepmistry/arduino-LoRa#41]
Your project arduino-LoRa is pretty interesting, the example of the sender an receiver are pretty well simplified :) 

I have some questions :

I don't relay know what type of Arduino card I should use... I have got an Arduino Mega2560, Due, and 101, actually I don't really understand how we can connect an sx1276 LoRa card to any type of Arduino cards without making some pin definitions in the codes (in the setup() parts of the codes should I use the LoRa.setPins(ss, reset, dio0)function ?) 

Thank you
Have a great day !

**Comment by sandeepmistry** [comment]
@KRolander please see https://github.com/sandeepmistry/arduino-LoRa#semtech-sx1276777879-wiring

Arduino Mega, Due, and 101 should be fine.
