### ISSUE TITLE
Get parity error result of Hamming code

### ISSUE THREAD

**Issue by connyoung** [sandeepmistry/arduino-LoRa#412]
Did you know how to get parity errors result when Hamming(6,4) or Hamming(5,4)?  I look forward to hearing from you. Thanks a lot.

**Comment by IoTThinks** [comment]
What is the context?

**Comment by connyoung** [comment]
when the coding rate is 5 or 6, the hamming code just can do error detection. So how can I get the error detection result?

**Comment by IoTThinks** [comment]
You mean CRC error?
If CRC error, can check this PR https://github.com/sandeepmistry/arduino-LoRa/pull/329

**Comment by connyoung** [comment]
Thanks.
