### ISSUE TITLE
Can we disable the Hamming Code?

### ISSUE THREAD

**Issue by connyoung** [sandeepmistry/arduino-LoRa#414]
How to disable the Hamming code? It means that sets the coding rate to 4/4. I look forward to hearing from you. Thanks a lot.

**Comment by IoTThinks** [comment]
I dont find any where in the datasheet mentioning about Hamming code?

Where do you read that from?

**Comment by IoTThinks** [comment]
Crc is default to be disabled anyway.

**Comment by IoTThinks** [comment]
Error correction is hard-coded into the LoRaWAN modem and as such cannot be disabled. To add a layer of user-defined FEC you would need to encode / decode the payload within the host MCU
https://lora-developers.semtech.com/knowledge-base/forum/viewthread/80/

**Comment by connyoung** [comment]
Thanks a lot!
