### ISSUE TITLE
Sending/receiving issues with TTGO LoRa32 Board (SX1276)

### ISSUE THREAD

**Issue by Kasperdelasopa** [sandeepmistry/arduino-LoRa#416]
Hello,

i tried to implement a Bi-directional communication. But at some point in time the communication doesn't seem to be reliable.
The communication i tried to accomplish is a request/respond scenario. It seems that the SX1276 Module stops receiving at some point in time.

It works most of the times but sometimes the two devices just doesn't send or receive.

Are there general communication rules, like "there needs to be a pause between sending and receiving"?

Best regards

**Comment by IoTThinks** [comment]
By default, LoRa.endPacket() will wait until a transmission completes.
After transmission, you can call LoRa.receive() again.

**Comment by orimate** [comment]
Hi, I have the same issue. I called extra LoRa.receive() after LoRa.endPacket() but does not helped.

**Comment by IoTThinks** [comment]
@orimate 
Check the sample code again.
The below code is incorrect.

onReceive(LoRa.parsePacket());
