### ISSUE TITLE
loraduplexcallback problem

### ISSUE THREAD

**Issue by huyle250398** [sandeepmistry/arduino-LoRa#419]
hi guys, I'm testing Loraduplexcallback between Arduino mega and esp8266. the problem is mega only sending and not receiving. has anyone got the same problem?

**Comment by huyle250398** [comment]
![image](https://user-images.githubusercontent.com/71761616/102501384-f7749800-40af-11eb-883d-5ac2367391c4.png)
my result on serial monitor

**Comment by IoTThinks** [comment]
Try the LoRaSender and LoRaReceiverCallback first.

Then swap the sender and receiver.

**Comment by huyle250398** [comment]
@IoTThinks ths bro, I tried that but esp cannot receive, so what probably the problem, mega still sending

**Comment by IoTThinks** [comment]
What is your pin mapping for LoRa in esp8266?

You can try to set the pin for SPI before LoRa.begin for esp8266.

SPI.begin(LORA_SCK, LORA_MISO, LORA_MOSI, LORA_SS);
LoRa.setPins(LORA_SS, LORA_RESET, LORA_DIO0);

**Comment by IoTThinks** [comment]
May try the D5-D8 of esp8266 for LoRa?

http://wei48221.blogspot.com/2017/09/esp8266-testing-spi-interface-using.html?m=1

**Comment by IoTThinks** [comment]
@huyle250398 How is the progress?

**Comment by huyle250398** [comment]
@IoTThinks ths bro, i tried with D5-D8 and it worked, 2 interrupt pin I used are D5 and D4
