### ISSUE TITLE
Multi-threaded data transfer

### ISSUE THREAD

**Issue by bolahg** [sandeepmistry/arduino-LoRa#426]
I need to transmit data on the same channel at the same time. How can this be implemented.
For example, with the nRF24L01 cards, you can organize a multithreaded connection in 6 channels. I need the same thing, but with the lora libraries

**Comment by IoTThinks** [comment]
AFAIK, no wireless chips and wired chips can "truly" send multiple packets in the same time.

You think it so as the bandwidth of the chip is fast enough and there is capability of re -transmission.

You need to finish transmitting a packet before sending another one.
The time on air is around few milliseconds to few seconds depending on the LoRa setting.

Moreover, SX1278 is half-duplex. You can't send while receiving and vice versa.

**Comment by bolahg** [comment]
thanks
