### ISSUE TITLE
Arduino Due fails 

### ISSUE THREAD

**Issue by Keyxss** [sandeepmistry/arduino-LoRa#427]
I am receiving `Starting LoRa failed` every time I run the program on my Arduino Due, but when I plug in Arduino Uno it works perfectly fine. I use Lo Ra-02 sx1278. I run the basic sender program and it fails. What could be the problem? Does in not work on Arduino Due?

**Comment by IoTThinks** [comment]
How do you so the wiring? Any screenshot?

Check if the Due uses 3.3v or 5v logic.
You may need logic converter if the board uses 5v logic.

Likely either wrong SPI wiring or logic level.

**Comment by Keyxss** [comment]
<img width="508" alt="Screenshot 2021-01-24 at 14 30 53" src="https://user-images.githubusercontent.com/77900431/105631872-e5290f00-5e50-11eb-8c7b-a955f5fcf35f.png">

**Comment by IoTThinks** [comment]
Double check the SPI pins.
![spi](https://user-images.githubusercontent.com/29994971/105660197-1bbc6380-5efd-11eb-9d5e-37e072660251.png)

Different Arduino boards (Nano, Uno, Mega, Due...) may have different SPI pins.

Your wiring seems to be for Uno instead.
![Arduino-Uno-R3-Pinouts](https://user-images.githubusercontent.com/29994971/105660298-4c040200-5efd-11eb-8af2-a966ca641b60.png)

**Comment by Keyxss** [comment]
<img width="599" alt="Screenshot 2021-01-25 at 09 13 30" src="https://user-images.githubusercontent.com/77900431/105678727-c3319a00-5eed-11eb-8587-9768e3bcf2f1.png">

I changed the pins according to that table, and it still does not work. Also I found here that Arduino UNO use 5v logic. Maybe that it the problem.

**Comment by IoTThinks** [comment]
3.3v logic is better than 5v logic.
For 5v logic boards, sometimes you need a logic converter to 3.3v.

Normally, only 3 issues:
1. Wrong SPI pins. Check if the DIO0 is wired to interruptable GPIO.
2. Wrong logic level. Sometimes, a logic converter to 3.3v is needed.
3. Not enough power for LoRa. Up to 100mA.

**Comment by Keyxss** [comment]
Somehow it worked. Thank you very much for your help

**Comment by IoTThinks** [comment]
@Keyxss How did you fix it?

**Comment by IoTThinks** [comment]
Ok enjoy.

**Comment by Keyxss** [comment]
Again thanks a lot for your time. It was my fault that I did not checked spi ports. I couldn't find anything on the internet. So I asked here.
