### ISSUE TITLE
Frequency Band P

### ISSUE THREAD

**Issue by DiegoDVG** [sandeepmistry/arduino-LoRa#433]
Hi, can I choose this band with this library 869,400 MHz to 869,650 MHz? because i can use  a dutty cicle like 10% an high power

Wich code i need?,  i so confused to choose a frecuency

thanks a lot

**Comment by IoTThinks** [comment]
Make sure you use 868/915Mhz chip.
Can set frequency to 869.4E6 or 869400000.
https://github.com/sandeepmistry/arduino-LoRa/blob/master/API.md#begin
