### ISSUE TITLE
LoRa Mesh protocol supports?

### ISSUE THREAD

**Issue by halukmy** [sandeepmistry/arduino-LoRa#446]
can we create mesh protocol with this lib?

**Comment by IoTThinks** [comment]
You need to define the mesh protocol yourself.

This library provides basic sending and receiving of LoRa packets.

**Comment by halukmy** [comment]
@IoTThinks  can you share this lib supported mesh examples please

**Comment by IoTThinks** [comment]
I dont have example of Mesh.

**Comment by sandeepmistry** [comment]
This is out of scope for this project.
