### ISSUE TITLE
Cant transmit, send packets -  loop stops while transmitting 1st packet

### ISSUE THREAD

**Issue by michalmutka** [sandeepmistry/arduino-LoRa#451]
I am using the example code for transmitting, but loop stops and waits for 1st packet to be sent, but it does not send. I got SX1276RFIAS and arduino UNO board wired as in description.

Any tips?
![screeeeeeen](https://user-images.githubusercontent.com/72385501/113269308-9c6e5600-92d8-11eb-94df-db66bfef7db8.png)

**Comment by IoTThinks** [comment]
Remove your code of flame sensor and try again.

**Comment by michalmutka** [comment]
> Why 1690E6?
> Highly doubt if LoRa supports over 950Mhz.

Sorry, thats a missclick. Even when I put 870 MHz or any other freq, it is the same.

**Comment by michalmutka** [comment]
> Why 1690E6?
> Highly doubt if LoRa supports over 950Mhz.

Already uploaded new photo with fixed code.

**Comment by IoTThinks** [comment]
Are you sure if the chip is not 433Mhz?

Remove your code of flame sensor  first.

Run the default example.

**Comment by michalmutka** [comment]
I tried, it is still the same, even without the flame sensor code.
Yes I am sure, the module SX1276RF1IAS supports two antenas -  one for 169MHz and one for 868 MHz. Neither of these frequencies work..
![bez](https://user-images.githubusercontent.com/72385501/113270487-cf651980-92d9-11eb-84ed-6d51d8a7dfca.png)

**Comment by IoTThinks** [comment]
Check this? https://github.com/sandeepmistry/arduino-LoRa/issues/47

**Comment by IoTThinks** [comment]
You can try to use LoRa.endPacket(true) to make sure the LoRa doesn't stuck at endPacket.
However, it seems the issue of the board not the library.
