### ISSUE TITLE
esp32-cam support?

### ISSUE THREAD

**Issue by halukmy** [sandeepmistry/arduino-LoRa#454]
can we transfor image or video ? anyone tried it before?

**Comment by IoTThinks** [comment]
LoRa is limited in bandwidth. Up to 27kbps.
The packet size is up to 255 bytes/packet.

Unless you can optimize your image and break the image into multiple packets to send.

**Comment by halukmy** [comment]
@IoTThinks thanks you friend, can you share example on api page please how to transform data to multiple packets

**Comment by IoTThinks** [comment]
You need to do it yourself.
