### ISSUE TITLE
ebyte e19 spi

### ISSUE THREAD

**Issue by hattafaiq** [sandeepmistry/arduino-LoRa#455]
has anyone tried using ebyte e19 with arduino?

**Comment by IoTThinks** [comment]
Check if the internal chip is sx127x.

**Comment by hattafaiq** [comment]
i am using ebyte e19-915m30s sx1276 and arduino pro micro 3.3v, but i can't find documentation about it using arduino. anybody help me to find library or documentation about it? thank you

**Comment by hattafaiq** [comment]
> Check if the internal chip is sx127x.

i am using ebyte e19-915m30s sx1276 and arduino pro micro 3.3v, but i can't find documentation about it using arduino. anybody help me to find library or documentation about it? thank you

**Comment by IoTThinks** [comment]
Try harder!

**Comment by IoTThinks** [comment]
https://github.com/sandeepmistry/arduino-LoRa
