### ISSUE TITLE
Difference Between  LoRa.print and  LoRa.write

### ISSUE THREAD

**Issue by BhargavDayal** [sandeepmistry/arduino-LoRa#457]
Hello 
I am just a beginner in programming .
I wanted to know the difference between the functions  LoRa.print and  LoRa.write

**Comment by IoTThinks** [comment]
I am also not sure.
I believe they are the same.

And LoRa.print may be for Arduino boards only.

https://github.com/sandeepmistry/arduino-LoRa/blob/master/API.md#writing

**Comment by BhargavDayal** [comment]
Hey thank you
