### ISSUE TITLE
[Question] Will it work with the E32-TTL-100?

### ISSUE THREAD

**Issue by philipgiuliani** [sandeepmistry/arduino-LoRa#46]
I am planning to buy this transceiver: https://www.banggood.com/433MHz-Wireless-Transceiver-Module-p-1172989.html?rmmds=detail-left-hotproducts

Will the hardware work with your library? If yes, how would I connect it?

**Comment by sandeepmistry** [comment]
@philipgiuliani no it will not work, it seems to have another MCU in front of the Semtech convert SPI to UART.
