### ISSUE TITLE
Why does not loop Txdone?

### ISSUE THREAD

**Issue by thanapol199717** [sandeepmistry/arduino-LoRa#462]
Hi everyone, I have tried these two code snippets in order to send and receive data between them. 

(https://github.com/sandeepmistry/arduino-LoRa/blob/master/examples/LoRaSimpleGateway/LoRaSimpleGateway.ino)
(https://github.com/sandeepmistry/arduino-LoRa/blob/master/examples/LoRaSimpleNode/LoRaSimpleNode.ino)

I think they both refuse to enter receiver mode as they keep on sending.

I'm using an Arduino nano with a SX1276.

**Comment by IoTThinks** [comment]
Try this https://github.com/sandeepmistry/arduino-LoRa/blob/master/examples/LoRaSenderNonBlockingCallback/LoRaSenderNonBlockingCallback.ino

And check if the TxDone is trigger.

**Comment by thanapol199717** [comment]
![image](https://user-images.githubusercontent.com/74811728/115659253-77fc1b80-a364-11eb-8af1-394ce9028286.png)

I think it's not a trigger.

**Comment by thanapol199717** [comment]
![image](https://user-images.githubusercontent.com/74811728/115663141-3cfce680-a36a-11eb-8414-b3a6e43f60d0.png)

![image](https://user-images.githubusercontent.com/74811728/115663192-54d46a80-a36a-11eb-8796-e739aab52bf2.png)

![image](https://user-images.githubusercontent.com/74811728/115663212-6158c300-a36a-11eb-8c5b-e1556874dccc.png)

![image](https://user-images.githubusercontent.com/74811728/115663257-76355680-a36a-11eb-9adc-3236eca14749.png)

![image](https://user-images.githubusercontent.com/74811728/115663293-82211880-a36a-11eb-8f8b-6035f91b6b67.png)

This  is my register.

**Comment by IoTThinks** [comment]
> ![image](https://user-images.githubusercontent.com/74811728/115659253-77fc1b80-a364-11eb-8af1-394ce9028286.png)
> 
> I think it's not a trigger.

Frankly speaking, I never use TxDone event. :dagger: 
From your image, TxDone is printed once. => Hence it is called once?

**Comment by thanapol199717** [comment]
Yes i don't know why.

**Comment by IoTThinks** [comment]
I will try with my esp32 + SX1276 this evening and see.

**Comment by thanapol199717** [comment]
Okay, thank you very much, I have to try to get a 3.3v supply for the SX1276 and I can use the Uno?

**Comment by IoTThinks** [comment]
Uno is better. Sx127x can use 3.3v supply from Uno.

**Comment by thanapol199717** [comment]
Okay, I'll try and tell you the results

**Comment by thanapol199717** [comment]
I have tried not enough from supply. Thank you so much. Do you have an example of a Raspberrypi Gateway that can reply to Arduino?
The same is true for the example I sent. But I want it to be Raspberrypi and Arduino to control my device.

Thank you for giving me new knowledge.

**Comment by IoTThinks** [comment]
So the TXDone works fine with external power on Arduino Nano?

**Comment by thanapol199717** [comment]
Yeah, I think so. I let sx1276 get 3.3v power from Uno, but the control is from Nano.

**Comment by IoTThinks** [comment]
Ok solved.
For the rest, you need to do some Google on your own first.

**Comment by thanapol199717** [comment]
Thank you very much.
