### ISSUE TITLE
lora communication

### ISSUE THREAD

**Issue by hoseinaghajari** [sandeepmistry/arduino-LoRa#468]
hi guys. I have confused these days by Lora Library. what I want to do is send and receive data with **SX1278 Module(https://cutt.ly/zbDX8K4)** and Arduino Uno. I can send data whenever I want and  the important thing for me is Low power consumption SO I can set my device in SLEEP_MODE after sending message. But I don't know how can I have low power consumption in receiving mode? 
see this: 
Rx..................>>
![55](https://user-images.githubusercontent.com/37798557/118453341-f5892200-b6ab-11eb-9bf7-29be530c8373.JPG)

 in this mode the device is always ON. so how can I alert my device for receiving data? I mean me device always sleep until a receiving packet has arrive.

**Comment by IoTThinks** [comment]
Use receivedCallback.
If DIO0 is high, wake the MCU up.

However, it will take 18mA when listening.

**Comment by hoseinaghajari** [comment]
@IoTThinks  you mean that use **onReceive()** function? According this picture from library example. is it necessary to use **LoRa.receive();** after  **onReceive()** ?
![9](https://user-images.githubusercontent.com/37798557/119253151-bd2e8b80-bb64-11eb-933f-309ac9136959.JPG)

**if yes; what about loop function? if I want to send message and waiting for answer, So it is necessary to call LoRa.receive(); after onReceive() In loop function? like this:
![10](https://user-images.githubusercontent.com/37798557/119253515-69bd3d00-bb66-11eb-8539-9894dfd9216f.JPG)

**Comment by IoTThinks** [comment]
You can read duplex callback example.

Btw, there are two RX modes.

After sending a message, you must set LoRa.receive() if using RX continious (aka Receive callback).

If you use Single RX, call parsePacket as frequent as possible.

**Comment by IoTThinks** [comment]
Note that you can only send or receive a packet at a time. Aka half duplex.

**Comment by hoseinaghajari** [comment]
my problem is the sender cant receive well after sending message. just that.

**Comment by IoTThinks** [comment]
Show the real photo of your board and antenna.

If already use the exact sample codes, then try to use an external power for LoRa. Likely insufficient power.

Arduino Nano?

**Comment by hoseinaghajari** [comment]
**sender code:**

![sender](https://user-images.githubusercontent.com/37798557/119254042-f79a2780-bb68-11eb-9b19-65a86aeea2ec.JPG)


**receiver code.**

![rec](https://user-images.githubusercontent.com/37798557/119254051-04b71680-bb69-11eb-9bc2-b00d8ad0528e.JPG)

**Comment by IoTThinks** [comment]
Read this again https://github.com/sandeepmistry/arduino-LoRa/blob/master/examples/LoRaDuplexCallback/LoRaDuplexCallback.ino

onReceive(LoRa.parsePacket()) is wrong to me.

**Comment by hoseinaghajari** [comment]
**_

thanks to you. I test again and tell you the result.

_**

**Comment by hoseinaghajari** [comment]
**how could I switch between tx mode and rx mode?
this is from datasheet. Does library do this?**
![wwwe](https://user-images.githubusercontent.com/37798557/119274834-c5b7ae00-bbc6-11eb-8b91-eacd686760a1.JPG)

**Comment by IoTThinks** [comment]
You can read the source code of this library.
Especially in BeginPacket (to send), ParsePacket(to receive in single RX) and LoRa.receive() (to receive in Continuous RX).

**Comment by hoseinaghajari** [comment]
I tested last night and I had problem again. I think the library can't support this kind of communication. I send message to node2 and node2 send his answer ( with Answer(); ) to node1. but after 3 or 4 times it corrupt. 
**_Node1:_** 
![lnf_t](https://user-images.githubusercontent.com/37798557/119298463-f3761480-bc11-11eb-8cb8-48efe4f337ae.JPG)

**_Node2:_**
![lnf2_t](https://user-images.githubusercontent.com/37798557/119298508-05f04e00-bc12-11eb-8d84-ad05e271d558.JPG)

**_the result from node1:_**
![LNF2](https://user-images.githubusercontent.com/37798557/119298616-3afca080-bc12-11eb-90d4-edf6acd461d0.JPG)
or:
![ln2](https://user-images.githubusercontent.com/37798557/119298652-494abc80-bc12-11eb-9f9f-5b4f04e97412.JPG)

**Comment by hoseinaghajari** [comment]
I have good power, I have good connection, but why? why it can send 6 or 7 time at first?

**Comment by IoTThinks** [comment]
I believe you are a newbie in programming. No offence, btw.
You need to try and explore for yourself a while.
Use the exact examples at first.

BTW, the bellow codes may have problems.
![image](https://user-images.githubusercontent.com/29994971/119299033-6a4df480-bc88-11eb-9111-4338b892be47.png)

and
![image](https://user-images.githubusercontent.com/29994971/119299151-95d0df00-bc88-11eb-95f0-713e781ce96d.png)

and don't try to send inside an ISR.
![image](https://user-images.githubusercontent.com/29994971/119299195-aaad7280-bc88-11eb-9d6d-54690a40145e.png)

**Comment by hoseinaghajari** [comment]
it is same as library example, why you said its wrong usage?
**_Library example:_**
![68](https://user-images.githubusercontent.com/37798557/119299966-caa34e80-bc14-11eb-8f96-ab74fcf7fde1.JPG)

**_![119299033-6a4df480-bc88-11eb-9111-4338b892be47](https://user-images.githubusercontent.com/37798557/119299987-d42cb680-bc14-11eb-9c1f-8219ebe7154e.png)_**

**Comment by hoseinaghajari** [comment]
**Is it need sth to add while changing tx mode to rx mode?**

**Comment by IoTThinks** [comment]
How many times the LoRa.receive() is called in your code and in the example code in 3 seconds?
LoRa.receive() is to set the LoRa into continuous RX mode.

You should find the datasheet of SX1276/1278 to read about the Single RX mode and Continuous mode.
Read the source code and try the **exact** example code.

> **_MY CODE_**
> **_![119299033-6a4df480-bc88-11eb-9111-4338b892be47](https://user-images.githubusercontent.com/37798557/119299987-d42cb680-bc14-11eb-9c1f-8219ebe7154e.png)_**

**Comment by hoseinaghajari** [comment]
hi guys. I fixed the problem and it work, as a reminder; node1 send hi to node2 and node2 answer it. it work now but take a look at my code please and tell me why ir stop working after 60 minutes? I Send 300 times at 1 hour. **after around 300 times sending, the Node2 cant receive message. why?**

**_Node1(Sender):_**

```
#include <SPI.h>
#include <LoRa.h>

unsigned char Hi[] = "Hi I'm Node1";
String inString = "";

void setup(){
  Serial.begin(9600);
  while (!Serial);
  Serial.println("LoRa gateway");
  if (!LoRa.begin(433E6)) {
    Serial.println("Starting LoRa failed!");
    while (1);
  }
}

void loop() {

  if(runEvery(10000))
  Send(Hi);

   int packetSize = LoRa.parsePacket();
  if (packetSize){
  Receive();
  }
}


void  Send(String Byte){
 ​LoRa.beginPacket();
 ​LoRa.print(Byte);
 ​LoRa.endPacket();
 ​Serial.println(Byte);
 ​}

void Receive(){
    Serial.print("received:  ");
    String incoming = "";
  while (LoRa.available()) {
    incoming += (char)LoRa.read();
               }
Serial.println(incoming);             ​
        }  

  
  boolean runEvery(unsigned long interval){
  static unsigned long previousMillis = 0;
  unsigned long currentMillis = millis();
  if (currentMillis - previousMillis >= interval){
    previousMillis = currentMillis;
    return true;
  }
  return false;
} 

```

**_Node2(Receiver):_**

```
#include <SPI.h>
#include <LoRa.h>

void setup() {
  Serial.begin(9600);
  while (!Serial);
  Serial.println("LoRa Sender");
  if (!LoRa.begin(433E6)){
    Serial.println("Starting LoRa failed!");
    while (1);
  }
}

void loop() {
    int packetSize = LoRa.parsePacket();
  if(packetSize){
  Receive();
  Answer();
  }
}

void Send(String Byte){
  LoRa.beginPacket();
  LoRa.print(Byte);
  LoRa.endPacket();
  }

void Receive(){
  String incoming = "";
  while (LoRa.available()) {
    incoming += (char)LoRa.read();
  }
  Serial.print("Received: " + incoming);
  }


void Answer(){
    String sendANswer = "I got it";
     Serial.print("   Send: ");
               Serial.println(sendANswer);  
                Send(sendANswer);
}


```

**_after around 300 times sending, the Node2 cant receive message. why?_**

**Comment by hoseinaghajari** [comment]
**_Dear @sandeepmistry please help me._**

**Comment by IoTThinks** [comment]
May be related and solved issue: https://github.com/sandeepmistry/arduino-LoRa/issues/363

**Comment by hoseinaghajari** [comment]
this problem was solved for me.
