### ISSUE TITLE
How to wake up the Lora Module

### ISSUE THREAD

**Issue by hkarthik97** [sandeepmistry/arduino-LoRa#473]
The library provides option for putting lora to sleep. How do i wake up?

**Comment by RubiRubsn** [comment]
via pulling down the reset pin

**Comment by IoTThinks** [comment]
How do you make LoRa module to sleep?
Via LoRa.end() or LoRa.sleep()?

**Comment by RubiRubsn** [comment]
@hkarthik97 I looked in the code, with LoRa.begin() you wake the module.

@IoTThinks with LoRa.sleep() you set the module in sleep mode. im not shure in wich mode the module consume less energy. (sleep or shutted down) you should measure that and test it ^^

**Comment by IoTThinks** [comment]
LoRa.end() will consume less energy than LoRa.sleep().
