### ISSUE TITLE
Starting LoRa failed! ESP8266 & RFM95W Version = 0

### ISSUE THREAD

**Issue by RubiRubsn** [sandeepmistry/arduino-LoRa#474]
Hi Guys,
I´ve tried to play a bit around with a RFM95W and a ESP8266. I wired the RFM to the ESP like that: SS->D8, SCK->D5, Mois->D7, Miso->D6, Dio0->D1, Reset->D2
I`ve used this example:

  int counter = 0;
  
  void setup()
  {
    sei();
    Serial.begin(9600);
    while (!Serial)
      ;
    LoRa.setPins(D8, D2, D1);
    Serial.println("LoRa Sender");
    long FREQ = 868E6;
    if (!LoRa.begin(FREQ))
    {
      Serial.println("Starting LoRa failed!");
      while (1)
        yield();
      ;
    }
  }
  
  void loop()
  {
    Serial.print("Sending packet: ");
    Serial.println(counter);
    // send packet
    LoRa.beginPacket();
    LoRa.print("hello ");
    LoRa.print(counter);
    LoRa.endPacket();
  
    counter++;
  
    delay(5000);
  }

I'am using PlatformIO.

I get a "Starting LoRa failed!" in the Serial monitor and after adding 

  uint8_t version = readRegister(REG_VERSION);
  Serial.print("version: ");
  Serial.println(version);

im getting "Version: 0"; 
Dumping my Register shows, the complete register is 0.

Maybe i have a problem with a connection but i double and Tribble checkt everything.

I bought this one: https://www.ebay.de/itm/254008635442?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2060353.m2749.l2649

I tried that with an Arduino Uno and have the same problem

Thanks for your help^^

**Comment by RubiRubsn** [comment]
found my Problem, had a cold soldering point. (on two modules, it was hard to find) thx for your help. :D

**Comment by ghebra** [comment]
please help me , how you are resolve this issue
