### ISSUE TITLE
CRC not working

### ISSUE THREAD

**Issue by m3g4by73** [sandeepmistry/arduino-LoRa#48]
I've enabled CRC on sender and receiver but I still get bad packets when at the limits of range. Is enabling CRC meant to ignore bad packets or do I need to check it manually in the OnReceive callback? I can't find a function for that in this library or it's documentation.

**Comment by sandeepmistry** [comment]
@m3g4by73 could you please share minimal sketches to reproduce the issue.

**Comment by sandeepmistry** [comment]
Closing for now due to lack of feedback, please re-open with requested info if you are still interested.
