### ISSUE TITLE
SPI frequency for Atmega32U4

### ISSUE THREAD

**Issue by dontsovcmc** [sandeepmistry/arduino-LoRa#51]
What SPI frequency I should use for Atmega32U4 8MGhz ?

Thanks a lot

**Comment by DzikuVx** [comment]
I'm using default SPI frequency without any problems.

**Comment by sandeepmistry** [comment]
@dontsovcmc please see @DzikuVx's comment above.

@DzikuVx thanks for answering :)

**Comment by dontsovcmc** [comment]
Thanks!
