### ISSUE TITLE
LoRa 1 channel gateway

### ISSUE THREAD

**Issue by jaimelaborda** [sandeepmistry/arduino-LoRa#53]
There is a way to block a node to a certain channel? I know with the LMIC IBM library you can. I have a one channel DIY gateway running on a Raspberry Pi, and I would like to block my node only to Channel 0 (868.1MHz) using that library I love.

Thanks!

**Comment by sandeepmistry** [comment]
@jaimelaborda this library has no concept of channels, you just send the radio parameters and they stay fixed unless you change them,
