### ISSUE TITLE
SPI half duplex pins

### ISSUE THREAD

**Issue by CodeOn-ArK** [sandeepmistry/arduino-LoRa#530]
Hello!
I don't have any issue, rather a question - the sx1278 SOC uses half duplex mode of communication so why are we using all the SPI pins? As far as I know to communicate in Half Duplex mode you need only one of the 2 data pins as shown here -
```shorturl.at/ivyzB```
So why are we using both the MOSI and MISO pins?
Thanks in advance

**Comment by CodeOn-ArK** [comment]
> Interesting question.
> 
> May be Semtech want to use I2C standard instead of reinventing the wheel?

wdym? Doesn't it uses SPI by default and is the only means of communication?

**Comment by IoTThinks** [comment]
@CodeOn-ArK My bad. SPI.
Already edited. Thanks a lot.

**Comment by morganrallen** [comment]
Not sure where this info is coming from but far as I can tell the SX127x series are full-duplex only.

![image](https://user-images.githubusercontent.com/22881/156379926-43383a10-0705-45b9-99fe-4f3ce7d38d43.png)
