### ISSUE TITLE
Is it possible to use two LoRa modules simultaneously on one Arduino?

### ISSUE THREAD

**Issue by NaomiGt** [sandeepmistry/arduino-LoRa#553]
Hi, I am working on a project where we would like to have two arduinos receive messages simultaneously. I've been looking into how we could use both modules with one Arduino UNO, but I cant figure out if it is possible and how to wire such a circuit.
I was wondering if this has ever been tried by someone else / if someone knows wether it could be done.

**Comment by benner** [comment]
https://github.com/sandeepmistry/arduino-LoRa/issues/548

**Comment by NaomiGt** [comment]
Thanks!
