### ISSUE TITLE
Starting LoRa failed

### ISSUE THREAD

**Issue by pramasenja** [sandeepmistry/arduino-LoRa#554]
Hi, i failed when tried to starting the LoRa. I tried using the demo code and using LoRa RFM95W with arduino mega 2560. I've used Logic level converter but it still failed to start.

And then i add `LoRa.setSPIFrequency(1E6)` and still failed to start. (Already tried from `8E6` to `1E6`)

And then i add `LoRa.setPins(10, 9, 2)` and still failed to start

Here is some pictures of my wiring.
![IMG_20220125_131614](https://user-images.githubusercontent.com/77260187/151759912-2c10d131-54c7-4897-a9f3-6931e6e1a6cb.jpg)
![IMG_20220125_131622](https://user-images.githubusercontent.com/77260187/151759919-f12cbaef-6217-4f38-8e26-c92e5bf2d2ea.jpg)
![IMG_20220125_131631](https://user-images.githubusercontent.com/77260187/151759927-07951d12-fb52-4e3f-b325-bb2ac7f1633c.jpg)

![IMG_20220125_131551](https://user-images.githubusercontent.com/77260187/151759882-d6672ba7-8d8f-4e4a-9705-177668a67243.jpg)
 
Here is my code :
```
#include <SPI.h>
#include <LoRa.h>

int counter = 0;

void setup() {
  Serial.begin(9600);
  while (!Serial);

  Serial.println("LoRa Sender");
  LoRa.setPins(10, 9, 2);
  LoRa.setSPIFrequency(1E6);
  if (!LoRa.begin(915E6)) {
    Serial.println("Starting LoRa failed!");
    while (1);
  }
}

void loop() {
  Serial.print("Sending packet: ");
  Serial.println(counter);

  // send packet
  LoRa.beginPacket();
  LoRa.print("hello ");
  LoRa.print(counter);
  LoRa.endPacket();

  counter++;

  delay(5000);
}
```
Sorry, I'm still a beginner at this.

**Comment by Kongduino** [comment]
It's hard to judge from the photos, but it looks like pins 9 and 10 have nothing connected to them.

**Comment by pramasenja** [comment]
Hi @Kongduino , Thanks for the help, but it still failed to start. (Starting LoRa Failed)

Sorry if my photos is not clear enough, this is the wiring schema picture : 
![Artboard 1](https://user-images.githubusercontent.com/77260187/152088797-29535c46-55d5-421b-8ba2-a4564b627bdd.jpg)

Sorry if the logic level converter image is different from the photo, but the pins is still the same.

And here is the current photos of lora and arduino :
![IMG_20220202_094738](https://user-images.githubusercontent.com/77260187/152089268-b3e57ad2-96e6-453b-9e01-49afac86352f.jpg)
![IMG_20220202_094756](https://user-images.githubusercontent.com/77260187/152089275-8d2dce58-8b85-45f1-8d52-4718e3670bef.jpg)
![IMG_20220202_094745](https://user-images.githubusercontent.com/77260187/152089277-bcb5356c-f511-4b7e-9636-32632d7fdae7.jpg)

**Comment by Kongduino** [comment]
The first issue I can see is that HV is connected to 3v3, whereas it should be connected to 5v. You're using a bidirectional logic converter for a reason: to convert between 5v and 3.3v... So on the HV side you need to give them a reference voltage that matches the level of the various pins, ie 5v.

**Comment by pramasenja** [comment]
Thanks for the explanation @Kongduino.
Should i use external power supply 5v?
i tried to move the pin to 5v, and it still failed.
![IMG_20220202_132838](https://user-images.githubusercontent.com/77260187/152105489-9a2d9158-c637-4aa2-835c-0815faacd9e6.jpg)
![1](https://user-images.githubusercontent.com/77260187/152105542-d3bdb42a-8ec3-45e7-8a8e-22358e85c49a.PNG)

**Comment by EsKliwoN** [comment]
i think i know what the problem is. The problem is in your Logic Converter.
I have same experience with that logic converter and my LoRa can not run properly. And i just realize that my Logic Converter doesn't support high Frequency for SPI communication that used by LoRa (MISO, MOSI, NSS, CLK).  Problem Solving :
1. Change your board with 3.3V working voltage like esp32 or STM32
2.  Try to change your logic converter with IC inside them. Like TXS0108E 8 Channel ( https://components101.com/modules/txs0108e-bi-directional-logic-level-converter-module )

**Comment by pramasenja** [comment]
Thanks @EsKliwoN , I will try to buy a board with 3.3v next week

**Comment by pramasenja** [comment]
Thank you @EsKliwoN , esp32 works fine.
I think the problem is in my Logic Converter.
I'm gonna close this issue

![Capture](https://user-images.githubusercontent.com/77260187/154397865-4aeaea4b-1386-4adc-b2f1-9d09fc981ad1.PNG)
![IMG_20220217_101043](https://user-images.githubusercontent.com/77260187/154397873-b13f9602-8c9a-4aa2-b1ec-48fc6c555ca0.jpg)
