### ISSUE TITLE
Is there a difference between using LoRa.print() and LoRa.write() ?

### ISSUE THREAD

**Issue by levycarneiro** [sandeepmistry/arduino-LoRa#555]
Is there a difference between using LoRa.print() and LoRa.write() ?

Thanks.

**Comment by Kongduino** [comment]
`print()`, as the name suggests, is for Strings or char arrays. A `0x00` will stop transmission. `write()` has 2 version:

```c
  virtual size_t write(uint8_t byte);
  virtual size_t write(const uint8_t *buffer, size_t size);
```

It either writes one byte, or a `buffer` of `size` bytes, regardless of the content.

**Comment by levycarneiro** [comment]
Clear now. Thanks very much, @Kongduino !
