### ISSUE TITLE
IRQ Pin Required for receiving?

### ISSUE THREAD

**Issue by kikolobo** [sandeepmistry/arduino-LoRa#572]
Hello, I am working on a pin constraint situation and I was wondering if the IRQ pin is required for poll receiving. I am looking at this example:

https://github.com/sandeepmistry/arduino-LoRa/blob/master/examples/LoRaDuplex/LoRaDuplex.ino

But it looks like it does not require the pin. I am also seeing that putting the device in (LoRa.receive()) is not required to see if you have received packets. 

I am also wondering if LoRa is full duplex or half duplex?

Thanks for any help in advance.

**Comment by IoTThinks** [comment]
OnReceive() requires DIO0.
ParsePacket does not.

LoRa sx126x and sx127x are half duplex.

**Comment by kikolobo** [comment]
> OnReceive() requires DIO0. ParsePacket does not.
> 
> LoRa sx126x and sx127x are half duplex.

Thank you.
