### ISSUE TITLE
Work with Helium

### ISSUE THREAD

**Issue by kargarisaac** [sandeepmistry/arduino-LoRa#579]
Hello,

Is it possible to use this library with Helium? I'm going to have a custom board with esp32-c3 board and looking for right library and lora module. Is there any recommendation?

Thanks

**Comment by Kongduino** [comment]
Definitely not. As mentioned, among other places, in the Readme, this is a raw LoRa (aka LoRa P2P, or LoRa PHY) library. It does not even do LoRaWAN, let alone other protocols. This is a great library for people who need a lightweight LoRa PHY library.

**Comment by kargarisaac** [comment]
> Definitely not. As mentioned, among other places, in the Readme, this is a raw LoRa (aka LoRa P2P, or LoRa PHY) library. It does not even do LoRaWAN, let alone other protocols. This is a great library for people who need a lightweight LoRa PHY library.

Thanks for the reply. What do you suggest to start with? I'm new and looking for a starting point.

**Comment by morganrallen** [comment]
> What do you suggest
Don't get involved in 'crypto' ponzi schemes.
