### ISSUE TITLE
Sync Word

### ISSUE THREAD

**Issue by rezakhosravi** [sandeepmistry/arduino-LoRa#58]
Hi,
It looks the Sync Word doesn't work correctly.
Please advice.
I am trying to make 2 privet LoRa network and separate them with Sync Word but both receiver receiving both senders message.

Thanks

**Comment by sandeepmistry** [comment]
@rezakhosravi please provide more details (example sketch to reproduce).

Seems like it's the same as #16, so I'm going to close as a duplicate until more details are available.
