### ISSUE TITLE
Examples with Addresses of just one Byte

### ISSUE THREAD

**Issue by ruiseixasm** [sandeepmistry/arduino-LoRa#593]
Hi,

I would like some examples with a full 16bits integer, 2 bytes for the address instead of just 1 byte as stated on your examples:
```
byte localAddress = 0xBB;     // address of this device
byte destination = 0xFF;      // destination to send to
```

The [LoRa specs](https://reyax.com/products/rylr896/) state:
```
AT+ADDRESS=<Address>
<Address>=0~65535(default 0)
```

One byte is too little, just 256 possible addresses!

Thanks

**Comment by Kongduino** [comment]
This module you link to is a managed module: you can see on the photo it has an MCU between the UART pins and the LoRa chip. The document you link to has nothing to do with the LoRa specs... There are no AT commands in LoRa. This is the AT firmware of this specific company for this specific MCU. And of course it has nothing to do with this library...
