### ISSUE TITLE
LoRa + Pro Micro Sleep issue

### ISSUE THREAD

**Issue by i-g-g-y** [sandeepmistry/arduino-LoRa#596]
Hello.

I have device with LoRa + Pro Micro (uses atmega32U4). I am running of a battery and noticed that after transmitting a packet, the bootloader is triggered and the atmega32U4 won't go to sleep. The bootloader uses USB and the mechanism first opens one com port for 8 seconds and then reopens another com port for application comm. This potentially means 2x wake-up.

**Comment by Kongduino** [comment]
How is your LoRa module connected to the ATmega? UART or SPI?

**Comment by i-g-g-y** [comment]
Hello.

My mistake! It was a power supply issue causing a mcu reset!

Sorry about that, I was sure psu is OK and went to check out of despair. It was not OK.
