### ISSUE TITLE
Hello my Friend San

### ISSUE THREAD

**Issue by spabon** [sandeepmistry/arduino-LoRa#6]
Good Afternoon My friend

I have a couple of RN2903 modules.
I want to connect them and transmit. Can I use the code to send and receive that you uploaded here? My modules have a frequency of 915 MHz.
Do you have a diagram to connect them?

I thank you, my friend.

**Comment by sandeepmistry** [comment]
@sabas1080 thanks for helping out!

@spabon please see @sabas1080's comment above as well as the info listed in the read me: https://github.com/sandeepmistry/arduino-LoRa#compatible-hardware
