### ISSUE TITLE
Compatible with LLCC68

### ISSUE THREAD

**Issue by garudaonekh** [sandeepmistry/arduino-LoRa#602]
HI,
Anyone get this working on LLCC68 chip? I try it with esp32 but it failed

Based on document, LLCC68 is a newer and much cheaper than SX1276/1278 and have better range.

Thanks.

**Comment by Kongduino** [comment]
Won't work. LLCC68 is compatible with SX1268, hence the name. This library is for the SX127x family.

**Comment by garudaonekh** [comment]
Thanks
