### ISSUE TITLE
Non blocking function to transmit

### ISSUE THREAD

**Issue by universam1** [sandeepmistry/arduino-LoRa#63]
The `endPacket()` is a blocking transmit that can take over 6 seconds depending on the radio settings. 
A non blocking version is proposed with MR #62 , tested successfully on ESP8266. 
Note the grace time required for the radio to properly update the registers.

Example added as well to demo.

**Comment by ainst** [comment]
Would it be possible to add a callback as well as part of the changes to endPacketAsync()? 

For example, I would like to turn receive back on once a transmit has been completed.

**Comment by torntrousers** [comment]
Agree with @ainst , a callback for tx done would make this async support much more useful.

**Comment by sandeepmistry** [comment]
Closed via #62.


> Would it be possible to add a callback as well as part of the changes to endPacketAsync()?

@ainst @torntrousers  please open a new pull request for this.
