### ISSUE TITLE
LoRa library incompatibilities with SD Card.

### ISSUE THREAD

**Issue by mariolopezp** [sandeepmistry/arduino-LoRa#634]
Good Morning,

I am developing a university project that consists on connecting two LoRa nodes, where the sender gathers data from different sensors and sends it to the receiver, that is connected to a PC that processes the data received.

In this project, I thought it would be nice to use the SD card slot that is already embedded in the TTGO-LoRa32-V2.1 board to have a more resilient system in case there are interferences or the radio interface fails. What I found out, is that both the SD library and Sd_fat library collide with the LoRa library, so I am unable to add this functionality to my project.
I checked that the pins of the LoRa SPI interface and the SD SPI interface dont collide.
Is there anything I am doing wrong, or that I should take into account? Or it is actually incompatible to use both the LoRa and SD capabilities of the board at the same time?

Thank you very much.

**Comment by morganrallen** [comment]
Glad to hear!
