### ISSUE TITLE
[question] onTxDone

### ISSUE THREAD

**Issue by homonto** [sandeepmistry/arduino-LoRa#655]
Hi,

I started playing/using this very nice library and I have a question: is "onTxDone": 

1. only telling" TX done, whatever the result on the receiver side is (received or not)
2. or, confirming: receiver got the packet

I am trying to implement acknowledged transmission and I am thinking about using onTxDone for that purpose but I am not sure if that really helps - unlike in ESPnow, where one can easily use "onTxDone" as ESPnow confirms the packet from the receiver to the sender.
Or do I have to program the receiver to explicitly send the message to the sender: "aloha, I got your message"

thank you

**Comment by morganrallen** [comment]
It only means the sender is done transmitting, it has no awareness of the receiving side.

**Comment by homonto** [comment]
thx
