### ISSUE TITLE
How to display packet of data onto UwTerminal which is sent from RM186 module? 

### ISSUE THREAD

**Issue by kajolH** [sandeepmistry/arduino-LoRa#7]
I just want to send packet of data from RM186 module which is programmed through Arduino to UwTerminal.
If anyone knows then it would be helpful.

**Comment by sandeepmistry** [comment]
Hi @kajolH,

Please see the read me for a list of compatible hardware: https://github.com/sandeepmistry/arduino-LoRa#compatible-hardware

The RM186 is not supported.

**Comment by kajolH** [comment]
hi @sandeepmistry
RM186 module is SX1272 based board.

**Comment by kajolH** [comment]
I want to communicate between two RM186 modules,from which one module is available on RM186 DVK and another is outside the DVK.
.If anyone having idea about it then let me know.

Thanks in advance.
