### ISSUE TITLE
Data Rate - Receiving only 256 Bytes per second 

### ISSUE THREAD

**Issue by Discoverideas** [sandeepmistry/arduino-LoRa#82]
Hi,

I am using LoRa module RA-02 and sending a 50kb file. I sending it to other side in 256 chunk. 
Issue is i can only receive 256 Bytes per sec when i can send 4 packets per sec. 

I am using the same library also not able to change bandwidth.

Thanks in advance!

**Comment by sandeepmistry** [comment]
@Discoverideas please provide the sketches you are using. 

Aside, LoRa has a really low bit rate, sending a 50 kB file is probably not a great idea ...

**Comment by Discoverideas** [comment]
Hi Sandeep,

Thanks for the response. We are interfacing ESP32 BLE with LoRa module. The purpose of the application is to connect ESP32 through BLE to mobile application and can send and receive data from other device on long range. 50 KB of file is basically a audio file. The system will be used as for chating and voice messaging. 

Below is the code
/*
    Based on Neil Kolban example for IDF: https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/tests/BLE%20Tests/SampleWrite.cpp
    Ported to Arduino ESP32 by Evandro Copercini
*/

#include <BLEDevice.h>
#include <BLEUtils.h>
#include <BLEServer.h>
#include <SPI.h>
#include <LoRa.h>
#include <TimeLib.h>

// See the following for generating UUIDs:
// https://www.uuidgenerator.net/

#define SERVICE_UUID        "4fafc201-1fb5-459e-8fcc-c5c9c331914b"
#define CHARACTERISTIC_UUID "beb5483e-36e1-4688-b7f5-ea07361b26a8"

uint8_t value = 0;
int count = 0; uint32_t totllenght = 0;
class MyCallbacks: public BLECharacteristicCallbacks {

    void onWrite(BLECharacteristic *pCharacteristic) {
      std::string msg_rcvd = pCharacteristic->getValue();
      int total_len = msg_rcvd.length();
      Serial.print("total_len= ");
      Serial.println(total_len);
      int first = 0;
      int chunk = 255;
      /*if (last <= total_len) {
        last = total_len;
        }*/

      while (first < total_len) {
        int last = first + chunk;
        if (last > total_len) {
          last  = total_len;
        }
        Serial.println("*********");
        Serial.print("First - ");
        Serial.println(first);
        Serial.print("Last - ");
        Serial.println(last);

        Serial.print(hour());
        Serial.print(":");
        Serial.print(minute());
        Serial.print(":");
        Serial.print(second());
        Serial.print(":");
        Serial.println(millis());

        LoRa.beginPacket();

        for (int i = first; i <= last; i++)
        {
          Serial.print(msg_rcvd[i]);
          LoRa.print(msg_rcvd[i]);
        }
        LoRa.endPacket();
        Serial.println();

        first = first + chunk + 1;
        //delay(1000);
      }
      Serial.println("####################################");
      /*int lenght = value.length();
        totllenght += lenght;
        if (value.length() > 0) {
        Serial.println("*********");
        Serial.print("New value: ");
        Serial.print(count);
        LoRa.beginPacket();
        for (int i = 0; i < value.length(); i++)
        {
          Serial.print(value[i]);
          LoRa.print(value[i]);
        }
        Serial.println();
        Serial.println("*********");
        count++;

        LoRa.endPacket();
        }
        Serial.println("totllenght= ");
        Serial.println(totllenght);*/
    }
};

//


BLECharacteristic *pCharacteristic;

void setup() {
  Serial.begin(115200);
  // BLEDevice::init("MyDevice2");
  Serial.println("1- Range extander device");
  Serial.println("2- BLE 4.0");
  Serial.println("3- Sx1278 for Long range");


  if (!LoRa.begin(433E6)) {
    Serial.println("Starting LoRa failed!");
    while (1);
  } else {
    Serial.println("LoRa started");
  }

  // register the receive callback
  //LoRa.onReceive(onReceive);

  // put the radio into receive mode
  //LoRa.receive();

  BLEDevice::init("MyDevice2");
  Serial.println("MyDevice2");
  BLEServer *pServer = BLEDevice::createServer();

  BLEService *pService = pServer->createService(SERVICE_UUID);

  pCharacteristic = pService->createCharacteristic(
                      CHARACTERISTIC_UUID,
                      BLECharacteristic::PROPERTY_READ |
                      BLECharacteristic::PROPERTY_WRITE |
                      BLECharacteristic::PROPERTY_NOTIFY |
                      BLECharacteristic::PROPERTY_INDICATE
                    );
  pCharacteristic->setCallbacks(new MyCallbacks());

  pCharacteristic->setValue("Hello World");
  pService->start();

  BLEAdvertising *pAdvertising = pServer->getAdvertising();
  pAdvertising->start();
  String send_msg = "Quick brown fox jumps over the lazy fox0123456789 Quick brown fox jumps over the lazy fox0123456789 Quick brown fox jumps over the lazy fox0123456789 Quick brown fox jumps over the lazy fox0123456789 Quick brown fox jumps over the lazy fox0123456789 Quick brown fox jumps over the lazy fox0123456789 Quick brown fox jumps over the lazy fox0123456789 Quick brown fox jumps over the lazy fox0123456789 Quick brown fox jumps over the lazy fox0123456789 Quick brown fox jumps over the lazy fox0123456789 Quick brown fox jumps over the lazy fox0123456789 Quick brown fox jumps over the lazy fox0123456789 Quick brown fox jumps over the lazy fox0123456789 Quick brown fox jumps over the lazy fox0123456789 Quick brown fox jumps over the lazy fox0123456789 Quick brown fox jumps over the lazy fox0123456789 Quick brown fox jumps over the lazy fox0123456789 Quick brown fox jumps over the lazy fox0123456789 Quick brown fox jumps over the lazy fox0123456789 Quick brown fox jumps over the lazy fox0123456789 Quick brown fox jumps over the lazy fox0123456789 Quick brown fox jumps over the lazy fox0123456789 Quick brown fox jumps over the lazy fox0123456789 Quick brown fox jumps over the lazy fox0123456789 Quick brown fox jumps over the lazy fox0123456789 Quick brown fox jumps over the lazy fox0123456789 Quick brown fox jumps over the lazy fox0123456789 Quick brown fox jumps over the lazy fox0123456789 Quick brown fox jumps over the lazy fox0123456789 Quick brown fox jumps over the lazy fox0123456789";
  sendToBle(send_msg);
}


void loop() {

  //Receive from LoRa and send to BLE
  int packetSize = LoRa.parsePacket();
  if (packetSize) {
    Serial.print("packetSize == ");
    Serial.println(packetSize);
    // received a packet
    Serial.println("Received packet '");
    Serial.print(hour());
    Serial.print(":");
    Serial.print(minute());
    Serial.print(":");
    Serial.print(second());
    Serial.print(":");
    Serial.println(millis());
    String msg = "";

    for (int i = 0; i < packetSize; i++) {
      char ch = (char)LoRa.read();
      msg += ch;
      Serial.print(ch);
    }
    int msg_length = msg.length() + 1;
    Serial.println("");
    Serial.print("Message Length - ");
    Serial.println(msg_length);
    char charbuf[msg_length];
    msg.toCharArray(charbuf, msg_length);
    pCharacteristic->setValue(charbuf);
    pCharacteristic->notify();
    Serial.println("");
  }

  //Call sendToBle manually

  // put your main code here, to run repeatedly:
  //pCharacteristic->setValue("Heloo");
  //pCharacteristic->notify();
  //value++;
  //delay(5000);
}

void onReceive(int packetSize) {
  // received a packet
  Serial.print("Received packet '");

  //int packetSize = LoRa.parsePacket();
  Serial.print("packetSize == ");
  Serial.println(packetSize);

  // read packet
  for (int i = 0; i < packetSize; i++) {
    Serial.print((char)LoRa.read());
  }
}

void sendToBle(String msg_rcvd) {
  int total_len = msg_rcvd.length();
  Serial.print("total_len= ");
  Serial.println(total_len);
  int first = 0;
  int chunk = 255;
  /*if (last <= total_len) {
    last = total_len;
    }*/

  while (first < total_len) {
    int last = first + chunk;
    if (last > total_len) {
      last  = total_len;
    }
    Serial.println("*********");
    Serial.print("First - ");
    Serial.println(first);
    Serial.print("Last - ");
    Serial.println(last);

    Serial.print(hour());
    Serial.print(":");
    Serial.print(minute());
    Serial.print(":");
    Serial.print(second());
    Serial.print(":");
    Serial.println(millis());

    LoRa.beginPacket();

    for (int i = first; i <= last; i++)
    {
      Serial.print(msg_rcvd[i]);
      LoRa.print(msg_rcvd[i]);
    }
    LoRa.endPacket();
    Serial.println();

    first = first + chunk + 1;
    delay(1000);
  }
  Serial.println("####################################");
}

If you have any suggestions regarding this please let me know.
Thanks,

**Comment by sandeepmistry** [comment]
Hi @Discoverideas,

Could you please provide a more minimal set of sketches to identify the issue? I don't have the ESP32 LoRa boards you are using and it would be easier to diagnose if the sketch has less dependencies.

**Comment by sandeepmistry** [comment]
Closing for now due to lack of activity.
