### ISSUE TITLE
Will it work with the NiceRF Lora610AES-100mW AES Encrypted Lora Long Range Wireless Transceiver Data Transmission Module

### ISSUE THREAD

**Issue by stafil** [sandeepmistry/arduino-LoRa#84]
I am planning to buy this transceiver:  http://www.nicerf.com/product_149_66.html
Will the hardware work with your library? thanks

**Comment by sandeepmistry** [comment]
@stafil it doesn't look compatible as it has a UART interface instead of SPI. They most likely have another MCU in front of the Semtech LoRa chip.
