### ISSUE TITLE
Experiencing a Race Condition

### ISSUE THREAD

**Issue by webhat** [sandeepmistry/arduino-LoRa#86]
I've been bothered by a bug which I found, which I think is a race condition, where the Arduino is reading the RFM95 quicker than the result is available.

The code in [src/Lora.cpp#506-520](https://github.com/sandeepmistry/arduino-LoRa/blob/master/src/LoRa.cpp#L506-L520) below doesn't wait long enough between chip select and SPI Transaction, meaning that the example code [src/LoRa.cpp#L86](https://github.com/sandeepmistry/arduino-LoRa/blob/master/src/LoRa.cpp#L86) results is a `0x00` rather than the expected `0x12`. Introducing a delay, 10ms, solves this for me.

```c++
uint8_t LoRaClass::singleTransfer(uint8_t address, uint8_t value)
{
  uint8_t response;

  digitalWrite(_ss, LOW);
// insert delay here
  SPI.beginTransaction(_spiSettings);
  SPI.transfer(address);
  response = SPI.transfer(value);
  SPI.endTransaction();

  digitalWrite(_ss, HIGH);

  return response;
}
```

For clarity I am only using code from this repository, no additional custom code.

**Comment by sandeepmistry** [comment]
@webhat interesting, what hardware are you using for:

- the Arduino or Arduino equivalent
- the Semtech side

**Comment by webhat** [comment]
I'm using a Geekcreit UNO, with a RFM95 board.

**Comment by sandeepmistry** [comment]
@webhat what are you using as the logic level converter?

Have you tried lowering the SPI frequency as per the read me? https://github.com/sandeepmistry/arduino-LoRa/blob/master/API.md#set-spi-frequency

**Comment by sandeepmistry** [comment]
Closing for now due to lack of activity.
