### ISSUE TITLE
Setting the broadcast frequency

### ISSUE THREAD

**Issue by 31warren** [sandeepmistry/arduino-LoRa#87]
Please advise how to set a default broadcast frequency e.g. 869.525

I am using this library with a MKR1300 board.

**Comment by webhat** [comment]
You can pass the frequency to `begin` as a `long`, so that would mean something like `LoRa.begin(869525000)`.

```c++
int LoRaClass::begin(long frequency)
```

**Comment by 31warren** [comment]
Thanks,
Just to confirm, in the LoRaSender example could I use

  if (!LoRa.begin(869.525000)) {
    Serial.println("Starting LoRa failed!");
    while (1);

**Comment by webhat** [comment]
No, you misunderstood. You don't want to use a `float` `869.525000`, you want to use a `long` `869525000`, without the decimal point.

```c++
if (!LoRa.begin(869525000)) { // NO decimal point
    Serial.println("Starting LoRa failed!");
    while (1);
}
```

**Comment by 31warren** [comment]
Thank you for your help.
