### ISSUE TITLE
starting lora failed

### ISSUE THREAD

**Issue by kumarippu** [sandeepmistry/arduino-LoRa#89]
how to check whether lora Ra01 ai thinker working or not

**Comment by KE6MTO** [comment]
Do you have DIO0 connected? I have the same modules (RA-01) and I couldn't get them to work properly until I hooked up the DIO0 line. I've gotten it to work on a Particle Proton and Adafruit M0 Feather.

**Comment by skndungu** [comment]
hey where did you connect it is there a default pin for DIO0

**Comment by KE6MTO** [comment]
I used a GPIO on the MCU that could be used for Interrupts. Then I passed the PIN assignments to the LoRa library.
