### ISSUE TITLE
Programming to ATTiny45

### ISSUE THREAD

**Issue by 3Dtj** [sandeepmistry/arduino-LoRa#92]
Is it feasible to use an ATTiny45 processor in place of an Arduino UNO to run your LoRa sketch?  The ATTiny45 allows only 4 programmable I/O pins but the sketch requires 5 pins (if incorporating a LED and push button) thus are the cs, reset, or irq pin optional or do I need a larger programmable processor (ie ATMega 32)?

**Comment by sandeepmistry** [comment]
@3Dtj it should work, but I've never tried it.

From https://github.com/sandeepmistry/arduino-LoRa/blob/master/API.md#set-pins

DIO0 and reset can be optional.
