### ISSUE TITLE
I have two LoRa Dragino modules and I can't get them to communicate with each other using this library

### ISSUE THREAD

**Issue by GurenMarkV** [sandeepmistry/arduino-LoRa#98]
I like your library as it is easy to configure all the settings to try and optimize distance. I have these two Arduino shields and can't get them to talk to each other using the Duplex or the send/receive code. Is there modifications that need to be made to the duplex code? I just uploaded the sample as is on both devices.

**Comment by halukmy** [comment]
you can n0t go and buy a dorji sx1278 f module!

**Comment by sandeepmistry** [comment]
Make sure to update the frequency passed into begin to match what your h/w is tuned for.

**Comment by KE6MTO** [comment]
All connections double checked including the DI0 line?

**Comment by GurenMarkV** [comment]
I will try the frequency change later on. Might take me a few weeks to get back to you. 

> All connections double checked including the DI0 line?

It's a shield so all the connections were as they should be. 
Using the RadioHead library I can get 20m. I wanted to try using this one to get 3km after some optimization on the code.

**Comment by sandeepmistry** [comment]
Ok, please try it out and re-open this issue if you still have problems.

**Comment by pallavisingh1998** [comment]
on using radiohead library range between two lora shields is very less. how to increase the range upto 1 km?
